package presentacion_administrador.vistas.reportes.reporte_carreras;

import com.github.lgooddatepicker.components.DatePicker;
import com.github.lgooddatepicker.components.DatePickerSettings;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import presentacion_administrador.componentes.PanelNavegacion;
import presentacion_administrador.componentes.registros.RegistroReportesBloqueo;

/**
 *
 * @author erwbyel
 */
public class VentanaReporteCarreras extends javax.swing.JPanel {

    private JFrame frame;
    private int paginaActual = 0;
    private int elementosPorPagina = 8;
    private List<RegistroReportesBloqueo> lista;

    /**
     * Creates new form VentanaBienvenida
     *
     * @param frame
     */
    public VentanaReporteCarreras(JFrame frame) {
        this.frame = frame;
        initComponents();
        PanelNavegacion pnlNavegacion = new PanelNavegacion(frame);
        add(pnlNavegacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 200));
        
        //objeto para elegir la fecha inicial
        DatePickerSettings inicioSettings = new DatePickerSettings();
        inicioSettings.setAllowEmptyDates(false);
        inicioSettings.setColorBackgroundWeekdayLabels(Color.LIGHT_GRAY, true);
        inicioSettings.setFormatForDatesCommonEra("dd-MM-yyyy");
        inicioSettings.setFontCalendarDateLabels(new Font("Arial", Font.PLAIN, 12));
        inicioSettings.setFontValidDate(new Font("Arial", Font.BOLD, 14));
        DatePicker datePickerInicio = new DatePicker(inicioSettings);
        add(datePickerInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 240, 40));

        //objeto para elegir la fecha final
        DatePickerSettings finalSettings = new DatePickerSettings();
        finalSettings.setAllowEmptyDates(false);
        finalSettings.setColorBackgroundWeekdayLabels(Color.LIGHT_GRAY, true);
        finalSettings.setFormatForDatesCommonEra("dd-MM-yyyy");
        finalSettings.setFontCalendarDateLabels(new Font("Arial", Font.PLAIN, 12));
        finalSettings.setFontValidDate(new Font("Arial", Font.BOLD, 14));
        DatePicker datePickerFin = new DatePicker(finalSettings);
        
        add(datePickerInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 240, 40));
        add(datePickerFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 240, 40));

        lista = this.getget();
        actualizarPagina();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBarraProceso = new presentacion_administrador.componentes.PanelRound();
        pnlUno = new presentacion_administrador.componentes.PanelRound();
        lblUno = new javax.swing.JLabel();
        pnlTituloOperacion = new presentacion_administrador.componentes.PanelRound();
        lblTituloOperacion = new javax.swing.JLabel();
        pnlContenidoOperacion = new presentacion_administrador.componentes.PanelRound();
        pnlTabla = new presentacion_administrador.componentes.PanelRound();
        lblNumero = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblVersion = new javax.swing.JLabel();
        pnlTablaContenido = new javax.swing.JPanel();
        btnAnteriorPagina = new presentacion_administrador.componentes.PanelRound();
        lblAnterior = new javax.swing.JLabel();
        btnSiguientePagina = new presentacion_administrador.componentes.PanelRound();
        lblSiguiente = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        lblCancelar = new javax.swing.JLabel();
        botonCancelar = new presentacion_administrador.componentes.BotonCancelar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(16, 20, 65));
        setMinimumSize(new java.awt.Dimension(1440, 1024));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1440, 1024));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBarraProceso.setBackground(new java.awt.Color(32, 39, 116));
        pnlBarraProceso.setRoundTopLeft(15);
        pnlBarraProceso.setRoundTopRight(15);
        pnlBarraProceso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlUno.setBackground(new java.awt.Color(25, 50, 178));
        pnlUno.setRoundBottomLeft(200);
        pnlUno.setRoundBottomRight(200);
        pnlUno.setRoundTopLeft(200);
        pnlUno.setRoundTopRight(200);

        lblUno.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblUno.setForeground(new java.awt.Color(255, 255, 255));
        lblUno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUno.setText("1");

        javax.swing.GroupLayout pnlUnoLayout = new javax.swing.GroupLayout(pnlUno);
        pnlUno.setLayout(pnlUnoLayout);
        pnlUnoLayout.setHorizontalGroup(
            pnlUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUno, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        pnlUnoLayout.setVerticalGroup(
            pnlUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUno, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlBarraProceso.add(pnlUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, 50));

        add(pnlBarraProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 190, 90, 70));

        pnlTituloOperacion.setBackground(new java.awt.Color(105, 111, 153));
        pnlTituloOperacion.setRoundTopLeft(20);
        pnlTituloOperacion.setRoundTopRight(20);

        lblTituloOperacion.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        lblTituloOperacion.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloOperacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloOperacion.setText("reporte de carreras");
        lblTituloOperacion.setToolTipText("");
        lblTituloOperacion.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout pnlTituloOperacionLayout = new javax.swing.GroupLayout(pnlTituloOperacion);
        pnlTituloOperacion.setLayout(pnlTituloOperacionLayout);
        pnlTituloOperacionLayout.setHorizontalGroup(
            pnlTituloOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTituloOperacion, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );
        pnlTituloOperacionLayout.setVerticalGroup(
            pnlTituloOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTituloOperacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        add(pnlTituloOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 620, 50));

        pnlContenidoOperacion.setBackground(new java.awt.Color(25, 30, 69));
        pnlContenidoOperacion.setRoundBottomLeft(20);
        pnlContenidoOperacion.setRoundBottomRight(20);

        pnlTabla.setBackground(new java.awt.Color(22, 27, 89));
        pnlTabla.setRoundBottomLeft(15);
        pnlTabla.setRoundBottomRight(15);
        pnlTabla.setRoundTopLeft(15);
        pnlTabla.setRoundTopRight(15);

        lblNumero.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        lblNumero.setForeground(new java.awt.Color(255, 255, 255));
        lblNumero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumero.setText("nombre del alumno");

        lblNombre.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre.setText("fecha de desbloqueo");

        lblVersion.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        lblVersion.setForeground(new java.awt.Color(255, 255, 255));
        lblVersion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVersion.setText("motivo");

        pnlTablaContenido.setBackground(new java.awt.Color(16, 20, 65));
        pnlTablaContenido.setLayout(new javax.swing.BoxLayout(pnlTablaContenido, javax.swing.BoxLayout.Y_AXIS));

        btnAnteriorPagina.setBackground(new java.awt.Color(255, 0, 51));
        btnAnteriorPagina.setRoundBottomLeft(15);
        btnAnteriorPagina.setRoundBottomRight(15);
        btnAnteriorPagina.setRoundTopLeft(15);
        btnAnteriorPagina.setRoundTopRight(15);
        btnAnteriorPagina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAnteriorPaginaMouseClicked(evt);
            }
        });

        lblAnterior.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        lblAnterior.setForeground(new java.awt.Color(255, 255, 255));
        lblAnterior.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnterior.setText("anterior");
        lblAnterior.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnAnteriorPaginaLayout = new javax.swing.GroupLayout(btnAnteriorPagina);
        btnAnteriorPagina.setLayout(btnAnteriorPaginaLayout);
        btnAnteriorPaginaLayout.setHorizontalGroup(
            btnAnteriorPaginaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        btnAnteriorPaginaLayout.setVerticalGroup(
            btnAnteriorPaginaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        btnSiguientePagina.setBackground(new java.awt.Color(25, 50, 178));
        btnSiguientePagina.setRoundBottomLeft(15);
        btnSiguientePagina.setRoundBottomRight(15);
        btnSiguientePagina.setRoundTopLeft(15);
        btnSiguientePagina.setRoundTopRight(15);
        btnSiguientePagina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSiguientePaginaMouseClicked(evt);
            }
        });

        lblSiguiente.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        lblSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        lblSiguiente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSiguiente.setText("siguiente");
        lblSiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnSiguientePaginaLayout = new javax.swing.GroupLayout(btnSiguientePagina);
        btnSiguientePagina.setLayout(btnSiguientePaginaLayout);
        btnSiguientePaginaLayout.setHorizontalGroup(
            btnSiguientePaginaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSiguiente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        btnSiguientePaginaLayout.setVerticalGroup(
            btnSiguientePaginaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        lblNombre1.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        lblNombre1.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre1.setText("fecha de bloqueo");

        javax.swing.GroupLayout pnlTablaLayout = new javax.swing.GroupLayout(pnlTabla);
        pnlTabla.setLayout(pnlTablaLayout);
        pnlTablaLayout.setHorizontalGroup(
            pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTablaLayout.createSequentialGroup()
                .addGroup(pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlTablaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAnteriorPagina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(176, 176, 176)
                        .addComponent(btnSiguientePagina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTablaLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlTablaContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlTablaLayout.createSequentialGroup()
                                .addComponent(lblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblVersion, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)))))
                .addGap(14, 14, 14))
        );
        pnlTablaLayout.setVerticalGroup(
            pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTablaLayout.createSequentialGroup()
                .addGroup(pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(pnlTablaContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSiguientePagina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnteriorPagina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlContenidoOperacionLayout = new javax.swing.GroupLayout(pnlContenidoOperacion);
        pnlContenidoOperacion.setLayout(pnlContenidoOperacionLayout);
        pnlContenidoOperacionLayout.setHorizontalGroup(
            pnlContenidoOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenidoOperacionLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(pnlTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        pnlContenidoOperacionLayout.setVerticalGroup(
            pnlContenidoOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenidoOperacionLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(pnlTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        add(pnlContenidoOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 1310, 620));

        lblCancelar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCancelar.setForeground(new java.awt.Color(255, 255, 255));
        lblCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCancelar.setText("regresar a inicio");
        lblCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCancelarMouseClicked(evt);
            }
        });
        add(lblCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 910, 400, 50));

        botonCancelar.setBackground(new java.awt.Color(212, 82, 82));
        add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 910, 400, 50));

        jLabel1.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("fecha fin");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, 230, 40));

        jLabel2.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("fecha inicio");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 230, 40));
    }// </editor-fold>//GEN-END:initComponents

    //opciones de navegacion
    private void lblCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelarMouseClicked
        presentacion_administrador.Controlador.mostrarVentanaInicio(frame);
    }//GEN-LAST:event_lblCancelarMouseClicked

    //opciones para la paginacion
    private void btnSiguientePaginaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSiguientePaginaMouseClicked
        if ((paginaActual + 1) * elementosPorPagina < lista.size()) {
            paginaActual++;
            actualizarPagina();
        }
    }//GEN-LAST:event_btnSiguientePaginaMouseClicked

    private void btnAnteriorPaginaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnteriorPaginaMouseClicked
        if (paginaActual > 0) {
            paginaActual--;
            actualizarPagina();
        }
    }//GEN-LAST:event_btnAnteriorPaginaMouseClicked

    private void actualizarPagina() {
        pnlTablaContenido.removeAll();
        int inicio = paginaActual * elementosPorPagina;
        int fin = Math.min(inicio + elementosPorPagina, lista.size());
        for (int i = inicio; i < fin; i++) {
            pnlTablaContenido.add(lista.get(i));
        }
        pnlTablaContenido.revalidate();
        pnlTablaContenido.repaint();
    }

    private List<RegistroReportesBloqueo> getget() {
        List<RegistroReportesBloqueo> listaNueva = new ArrayList<>();
        for (int i = 0; i < 10; i++) {
            RegistroReportesBloqueo reporte = new RegistroReportesBloqueo(String.valueOf(i), "MINECRAFT", "1.20.1");
            listaNueva.add(reporte);
        }
        return listaNueva;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private presentacion_administrador.componentes.BotonCancelar botonCancelar;
    private presentacion_administrador.componentes.PanelRound btnAnteriorPagina;
    private presentacion_administrador.componentes.PanelRound btnSiguientePagina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAnterior;
    private javax.swing.JLabel lblCancelar;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblSiguiente;
    private javax.swing.JLabel lblTituloOperacion;
    private javax.swing.JLabel lblUno;
    private javax.swing.JLabel lblVersion;
    private presentacion_administrador.componentes.PanelRound pnlBarraProceso;
    private presentacion_administrador.componentes.PanelRound pnlContenidoOperacion;
    private presentacion_administrador.componentes.PanelRound pnlTabla;
    private javax.swing.JPanel pnlTablaContenido;
    private presentacion_administrador.componentes.PanelRound pnlTituloOperacion;
    private presentacion_administrador.componentes.PanelRound pnlUno;
    // End of variables declaration//GEN-END:variables
}
