package presentacion_administrador.vistas.bloqueos.agregar_bloqueo;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import presentacion_administrador.componentes.PanelNavegacion;

/**
 *
 * @author erwbyel
 */
public class VentanaBloqueoAgrega extends javax.swing.JPanel {

    private JFrame frame;

    /**
     * Creates new form VentanaBienvenida
     *
     * @param frame
     */
    public VentanaBloqueoAgrega(JFrame frame) {
        this.frame = frame;
        initComponents();
        PanelNavegacion pnlNavegacion = new PanelNavegacion(frame);
        add(pnlNavegacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 200));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBarraProceso = new presentacion_administrador.componentes.PanelRound();
        pnlUno = new presentacion_administrador.componentes.PanelRound();
        lblUno = new javax.swing.JLabel();
        pnlDos = new presentacion_administrador.componentes.PanelRound();
        lblDos = new javax.swing.JLabel();
        separadorUnoDos = new javax.swing.JPanel();
        pnlTituloOperacion = new presentacion_administrador.componentes.PanelRound();
        lblTituloOperacion = new javax.swing.JLabel();
        pnlContenidoOperacion = new presentacion_administrador.componentes.PanelRound();
        pnlEntradaId = new presentacion_administrador.componentes.PanelRound();
        lblId = new javax.swing.JLabel();
        txfId = new javax.swing.JTextField();
        pnlEntradaMotivo = new presentacion_administrador.componentes.PanelRound();
        lblMotivo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lblCancelar = new javax.swing.JLabel();
        botonCancelar = new presentacion_administrador.componentes.BotonCancelar();
        lblContinuar = new javax.swing.JLabel();
        botonContinuar = new presentacion_administrador.componentes.BotonSiguiente();

        setBackground(new java.awt.Color(16, 20, 65));
        setMinimumSize(new java.awt.Dimension(1440, 1024));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1440, 1024));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBarraProceso.setBackground(new java.awt.Color(32, 39, 116));
        pnlBarraProceso.setRoundTopLeft(15);
        pnlBarraProceso.setRoundTopRight(15);
        pnlBarraProceso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlUno.setBackground(new java.awt.Color(25, 50, 178));
        pnlUno.setRoundBottomLeft(200);
        pnlUno.setRoundBottomRight(200);
        pnlUno.setRoundTopLeft(200);
        pnlUno.setRoundTopRight(200);

        lblUno.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblUno.setForeground(new java.awt.Color(255, 255, 255));
        lblUno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUno.setText("1");

        javax.swing.GroupLayout pnlUnoLayout = new javax.swing.GroupLayout(pnlUno);
        pnlUno.setLayout(pnlUnoLayout);
        pnlUnoLayout.setHorizontalGroup(
            pnlUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUno, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        pnlUnoLayout.setVerticalGroup(
            pnlUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUno, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlBarraProceso.add(pnlUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, 50));

        pnlDos.setBackground(new java.awt.Color(105, 111, 153));
        pnlDos.setRoundBottomLeft(200);
        pnlDos.setRoundBottomRight(200);
        pnlDos.setRoundTopLeft(200);
        pnlDos.setRoundTopRight(200);

        lblDos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDos.setForeground(new java.awt.Color(255, 255, 255));
        lblDos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDos.setText("2");

        javax.swing.GroupLayout pnlDosLayout = new javax.swing.GroupLayout(pnlDos);
        pnlDos.setLayout(pnlDosLayout);
        pnlDosLayout.setHorizontalGroup(
            pnlDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDos, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        pnlDosLayout.setVerticalGroup(
            pnlDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDos, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlBarraProceso.add(pnlDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 50, 50));

        separadorUnoDos.setBackground(new java.awt.Color(105, 111, 153));

        javax.swing.GroupLayout separadorUnoDosLayout = new javax.swing.GroupLayout(separadorUnoDos);
        separadorUnoDos.setLayout(separadorUnoDosLayout);
        separadorUnoDosLayout.setHorizontalGroup(
            separadorUnoDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        separadorUnoDosLayout.setVerticalGroup(
            separadorUnoDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlBarraProceso.add(separadorUnoDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 90, -1));

        add(pnlBarraProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 190, 210, 70));

        pnlTituloOperacion.setBackground(new java.awt.Color(105, 111, 153));
        pnlTituloOperacion.setRoundTopLeft(20);
        pnlTituloOperacion.setRoundTopRight(20);

        lblTituloOperacion.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        lblTituloOperacion.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloOperacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloOperacion.setText("bloquear alumno");
        lblTituloOperacion.setToolTipText("");
        lblTituloOperacion.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout pnlTituloOperacionLayout = new javax.swing.GroupLayout(pnlTituloOperacion);
        pnlTituloOperacion.setLayout(pnlTituloOperacionLayout);
        pnlTituloOperacionLayout.setHorizontalGroup(
            pnlTituloOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTituloOperacion, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );
        pnlTituloOperacionLayout.setVerticalGroup(
            pnlTituloOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTituloOperacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        add(pnlTituloOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 620, 50));

        pnlContenidoOperacion.setBackground(new java.awt.Color(25, 30, 69));
        pnlContenidoOperacion.setRoundBottomLeft(20);
        pnlContenidoOperacion.setRoundBottomRight(20);

        pnlEntradaId.setBackground(new java.awt.Color(98, 102, 141));
        pnlEntradaId.setRoundBottomLeft(15);
        pnlEntradaId.setRoundBottomRight(15);
        pnlEntradaId.setRoundTopLeft(15);
        pnlEntradaId.setRoundTopRight(15);

        lblId.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        lblId.setForeground(new java.awt.Color(255, 255, 255));
        lblId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblId.setText("id alumno");
        lblId.setToolTipText("");

        txfId.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txfId.setForeground(new java.awt.Color(153, 153, 153));
        txfId.setText("  ingrese el id del alumno");
        txfId.setBorder(null);

        javax.swing.GroupLayout pnlEntradaIdLayout = new javax.swing.GroupLayout(pnlEntradaId);
        pnlEntradaId.setLayout(pnlEntradaIdLayout);
        pnlEntradaIdLayout.setHorizontalGroup(
            pnlEntradaIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEntradaIdLayout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(txfId, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(pnlEntradaIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlEntradaIdLayout.createSequentialGroup()
                    .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 597, Short.MAX_VALUE)))
        );
        pnlEntradaIdLayout.setVerticalGroup(
            pnlEntradaIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEntradaIdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txfId, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlEntradaIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlEntradaIdLayout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(lblId, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addGap(8, 8, 8)))
        );

        pnlEntradaMotivo.setBackground(new java.awt.Color(98, 102, 141));
        pnlEntradaMotivo.setRoundBottomLeft(15);
        pnlEntradaMotivo.setRoundBottomRight(15);
        pnlEntradaMotivo.setRoundTopLeft(15);
        pnlEntradaMotivo.setRoundTopRight(15);

        lblMotivo.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        lblMotivo.setForeground(new java.awt.Color(255, 255, 255));
        lblMotivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMotivo.setText("motivo del bloqueo");
        lblMotivo.setToolTipText("");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setToolTipText("");
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout pnlEntradaMotivoLayout = new javax.swing.GroupLayout(pnlEntradaMotivo);
        pnlEntradaMotivo.setLayout(pnlEntradaMotivoLayout);
        pnlEntradaMotivoLayout.setHorizontalGroup(
            pnlEntradaMotivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEntradaMotivoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(pnlEntradaMotivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlEntradaMotivoLayout.createSequentialGroup()
                    .addComponent(lblMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 468, Short.MAX_VALUE)))
        );
        pnlEntradaMotivoLayout.setVerticalGroup(
            pnlEntradaMotivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEntradaMotivoLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(pnlEntradaMotivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlEntradaMotivoLayout.createSequentialGroup()
                    .addComponent(lblMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 416, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout pnlContenidoOperacionLayout = new javax.swing.GroupLayout(pnlContenidoOperacion);
        pnlContenidoOperacion.setLayout(pnlContenidoOperacionLayout);
        pnlContenidoOperacionLayout.setHorizontalGroup(
            pnlContenidoOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenidoOperacionLayout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addGroup(pnlContenidoOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlEntradaId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlEntradaMotivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        pnlContenidoOperacionLayout.setVerticalGroup(
            pnlContenidoOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenidoOperacionLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(pnlEntradaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlEntradaMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        add(pnlContenidoOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 1310, 630));

        lblCancelar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCancelar.setForeground(new java.awt.Color(255, 255, 255));
        lblCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCancelar.setText("cancelar");
        lblCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCancelarMouseClicked(evt);
            }
        });
        add(lblCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 910, 330, 50));

        botonCancelar.setBackground(new java.awt.Color(212, 82, 82));
        add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 910, 330, 50));

        lblContinuar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblContinuar.setForeground(new java.awt.Color(255, 255, 255));
        lblContinuar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContinuar.setText("continuar");
        lblContinuar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(lblContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 910, 320, 50));

        botonContinuar.setBackground(new java.awt.Color(25, 50, 178));
        botonContinuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonContinuarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout botonContinuarLayout = new javax.swing.GroupLayout(botonContinuar);
        botonContinuar.setLayout(botonContinuarLayout);
        botonContinuarLayout.setHorizontalGroup(
            botonContinuarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        botonContinuarLayout.setVerticalGroup(
            botonContinuarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        add(botonContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 910, 320, 50));
    }// </editor-fold>//GEN-END:initComponents

    //opciones de navegacion
    private void lblCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelarMouseClicked
        presentacion_administrador.Controlador.mostrarVentanaInicio(frame);
    }//GEN-LAST:event_lblCancelarMouseClicked

    private void botonContinuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonContinuarMouseClicked
        mostrarVentanaBloqueoAgregaConfirmacion(frame);
    }//GEN-LAST:event_botonContinuarMouseClicked

    /**
     * ventana que permite continuar el proceso de agregar un bloqueo
     *
     * @param frame
     */
    public static void mostrarVentanaBloqueoAgregaConfirmacion(JFrame frame) {
        SwingUtilities.invokeLater(() -> {
            VentanaBloqueoAgregaConfirmar ventana = new VentanaBloqueoAgregaConfirmar(frame);
            frame.setContentPane(ventana);
            frame.revalidate();
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private presentacion_administrador.componentes.BotonCancelar botonCancelar;
    private presentacion_administrador.componentes.BotonSiguiente botonContinuar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblCancelar;
    private javax.swing.JLabel lblContinuar;
    private javax.swing.JLabel lblDos;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblMotivo;
    private javax.swing.JLabel lblTituloOperacion;
    private javax.swing.JLabel lblUno;
    private presentacion_administrador.componentes.PanelRound pnlBarraProceso;
    private presentacion_administrador.componentes.PanelRound pnlContenidoOperacion;
    private presentacion_administrador.componentes.PanelRound pnlDos;
    private presentacion_administrador.componentes.PanelRound pnlEntradaId;
    private presentacion_administrador.componentes.PanelRound pnlEntradaMotivo;
    private presentacion_administrador.componentes.PanelRound pnlTituloOperacion;
    private presentacion_administrador.componentes.PanelRound pnlUno;
    private javax.swing.JPanel separadorUnoDos;
    private javax.swing.JTextField txfId;
    // End of variables declaration//GEN-END:variables
}
