
package presentacion.vistas;



/**
 *
 * @author angel
 */
public class pnlBloqueo extends javax.swing.JPanel {

    /**
     * Creates new form pnlBloqueo
     */
    public pnlBloqueo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        pnlProgramaVersion = new javax.swing.JPanel();
        lblProgramaVersion = new javax.swing.JLabel();
        pnlEstadoComputadora = new presentacion.componentes.PanelRound();
        lblEstadoComputadora = new javax.swing.JLabel();
        pnlNumComputadora = new presentacion.componentes.PanelRound();
        lblNumComputadora = new javax.swing.JLabel();
        lblImgCisco = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(0, 0, 153));
        setMinimumSize(new java.awt.Dimension(1440, 1024));
        setPreferredSize(new java.awt.Dimension(1440, 1024));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlProgramaVersion.setBackground(new java.awt.Color(0, 0, 0));

        lblProgramaVersion.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        lblProgramaVersion.setForeground(new java.awt.Color(255, 255, 255));
        lblProgramaVersion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProgramaVersion.setText("software version 1.20.16v");

        javax.swing.GroupLayout pnlProgramaVersionLayout = new javax.swing.GroupLayout(pnlProgramaVersion);
        pnlProgramaVersion.setLayout(pnlProgramaVersionLayout);
        pnlProgramaVersionLayout.setHorizontalGroup(
            pnlProgramaVersionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProgramaVersionLayout.createSequentialGroup()
                .addContainerGap(1099, Short.MAX_VALUE)
                .addComponent(lblProgramaVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlProgramaVersionLayout.setVerticalGroup(
            pnlProgramaVersionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProgramaVersionLayout.createSequentialGroup()
                .addComponent(lblProgramaVersion, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(pnlProgramaVersion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 964, 1440, 60));

        pnlEstadoComputadora.setBackground(new java.awt.Color(7, 134, 0,215));
        pnlEstadoComputadora.setRoundTopRight(50);

        lblEstadoComputadora.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        lblEstadoComputadora.setForeground(new java.awt.Color(255, 255, 255,240));
        lblEstadoComputadora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstadoComputadora.setText("equipo disponible");

        javax.swing.GroupLayout pnlEstadoComputadoraLayout = new javax.swing.GroupLayout(pnlEstadoComputadora);
        pnlEstadoComputadora.setLayout(pnlEstadoComputadoraLayout);
        pnlEstadoComputadoraLayout.setHorizontalGroup(
            pnlEstadoComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEstadoComputadoraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEstadoComputadora, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlEstadoComputadoraLayout.setVerticalGroup(
            pnlEstadoComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEstadoComputadoraLayout.createSequentialGroup()
                .addComponent(lblEstadoComputadora, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        add(pnlEstadoComputadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 570, 50));

        pnlNumComputadora.setBackground(new java.awt.Color(0, 0, 0,215));

        lblNumComputadora.setFont(new java.awt.Font("MS UI Gothic", 1, 360)); // NOI18N
        lblNumComputadora.setForeground(new java.awt.Color(255, 255, 255,240));
        lblNumComputadora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumComputadora.setText("99");

        javax.swing.GroupLayout pnlNumComputadoraLayout = new javax.swing.GroupLayout(pnlNumComputadora);
        pnlNumComputadora.setLayout(pnlNumComputadoraLayout);
        pnlNumComputadoraLayout.setHorizontalGroup(
            pnlNumComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNumComputadoraLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblNumComputadora, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlNumComputadoraLayout.setVerticalGroup(
            pnlNumComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNumComputadoraLayout.createSequentialGroup()
                .addComponent(lblNumComputadora, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(pnlNumComputadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 570, 380));

        lblImgCisco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/cisco (3).jpg"))); // NOI18N
        add(lblImgCisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 964));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblEstadoComputadora;
    private javax.swing.JLabel lblImgCisco;
    private javax.swing.JLabel lblNumComputadora;
    private javax.swing.JLabel lblProgramaVersion;
    private presentacion.componentes.PanelRound pnlEstadoComputadora;
    private presentacion.componentes.PanelRound pnlNumComputadora;
    private javax.swing.JPanel pnlProgramaVersion;
    // End of variables declaration//GEN-END:variables
}
