
package presentacion.vistas;


/**
 * clase que modela las pantallas
 * @author erwbyel
 */
public class VentanaBloqueo extends javax.swing.JPanel {

    private java.awt.Color colorIn = new java.awt.Color(7, 134, 0, 255);
    private java.awt.Color colorOut = new java.awt.Color(7, 134, 0, 215);
    
    
    /**
     * Creates new form pnlBloqueo
     */
    public VentanaBloqueo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        pnlProgramaVersion = new javax.swing.JPanel();
        lblProgramaVersion = new javax.swing.JLabel();
        pnlEstadoComputadora = new presentacion.componentes.PanelRound();
        lblEstado = new javax.swing.JLabel();
        pnlNumComputadora = new presentacion.componentes.PanelRound();
        lblNumComputadora = new javax.swing.JLabel();
        pnlUsuarioReservado = new presentacion.componentes.PanelRound();
        lblUsuarioReservado = new javax.swing.JLabel();
        pnlLogin = new presentacion.componentes.PanelRound();
        lblIngreseContraseña = new javax.swing.JLabel();
        txfContraseña = new javax.swing.JTextField();
        btnIngresar = new presentacion.componentes.PanelRound();
        lblIngresar = new javax.swing.JLabel();
        lblImgCisco = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(0, 0, 153));
        setMinimumSize(new java.awt.Dimension(1440, 1024));
        setPreferredSize(new java.awt.Dimension(1440, 1024));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlProgramaVersion.setBackground(new java.awt.Color(0, 0, 0));

        lblProgramaVersion.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        lblProgramaVersion.setForeground(new java.awt.Color(255, 255, 255));
        lblProgramaVersion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProgramaVersion.setText("software version 1.20.16v");

        javax.swing.GroupLayout pnlProgramaVersionLayout = new javax.swing.GroupLayout(pnlProgramaVersion);
        pnlProgramaVersion.setLayout(pnlProgramaVersionLayout);
        pnlProgramaVersionLayout.setHorizontalGroup(
            pnlProgramaVersionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProgramaVersionLayout.createSequentialGroup()
                .addContainerGap(1099, Short.MAX_VALUE)
                .addComponent(lblProgramaVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlProgramaVersionLayout.setVerticalGroup(
            pnlProgramaVersionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProgramaVersionLayout.createSequentialGroup()
                .addComponent(lblProgramaVersion, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(pnlProgramaVersion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 964, 1440, 60));

        pnlEstadoComputadora.setBackground(new java.awt.Color(7, 134, 0, 215));
        pnlEstadoComputadora.setRoundTopRight(50);

        lblEstado.setFont(new java.awt.Font("MS UI Gothic", 1, 30)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(255, 255, 255,240));
        lblEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstado.setText("equipo disponible");

        javax.swing.GroupLayout pnlEstadoComputadoraLayout = new javax.swing.GroupLayout(pnlEstadoComputadora);
        pnlEstadoComputadora.setLayout(pnlEstadoComputadoraLayout);
        pnlEstadoComputadoraLayout.setHorizontalGroup(
            pnlEstadoComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEstadoComputadoraLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlEstadoComputadoraLayout.setVerticalGroup(
            pnlEstadoComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEstadoComputadoraLayout.createSequentialGroup()
                .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        add(pnlEstadoComputadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 570, 50));

        pnlNumComputadora.setBackground(new java.awt.Color(0, 0, 0,215));

        lblNumComputadora.setFont(new java.awt.Font("MS UI Gothic", 1, 360)); // NOI18N
        lblNumComputadora.setForeground(new java.awt.Color(255, 255, 255,240));
        lblNumComputadora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumComputadora.setText("99");

        javax.swing.GroupLayout pnlNumComputadoraLayout = new javax.swing.GroupLayout(pnlNumComputadora);
        pnlNumComputadora.setLayout(pnlNumComputadoraLayout);
        pnlNumComputadoraLayout.setHorizontalGroup(
            pnlNumComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNumComputadoraLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblNumComputadora, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlNumComputadoraLayout.setVerticalGroup(
            pnlNumComputadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNumComputadoraLayout.createSequentialGroup()
                .addComponent(lblNumComputadora, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        add(pnlNumComputadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 570, -1));

        pnlUsuarioReservado.setBackground(new java.awt.Color(7, 134, 0, 215));
        pnlUsuarioReservado.setRoundTopLeft(50);

        lblUsuarioReservado.setFont(new java.awt.Font("MS UI Gothic", 1, 30)); // NOI18N
        lblUsuarioReservado.setForeground(new java.awt.Color(255, 255, 255,240));
        lblUsuarioReservado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuarioReservado.setText("contraseña maestra");

        javax.swing.GroupLayout pnlUsuarioReservadoLayout = new javax.swing.GroupLayout(pnlUsuarioReservado);
        pnlUsuarioReservado.setLayout(pnlUsuarioReservadoLayout);
        pnlUsuarioReservadoLayout.setHorizontalGroup(
            pnlUsuarioReservadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuarioReservadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuarioReservado, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlUsuarioReservadoLayout.setVerticalGroup(
            pnlUsuarioReservadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUsuarioReservado, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        add(pnlUsuarioReservado, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 540, 570, 50));

        pnlLogin.setBackground(new java.awt.Color(0, 0, 0,215));

        lblIngreseContraseña.setFont(new java.awt.Font("MS UI Gothic", 1, 30)); // NOI18N
        lblIngreseContraseña.setForeground(new java.awt.Color(255, 255, 255,240));
        lblIngreseContraseña.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblIngreseContraseña.setText("ingrese contraseña");

        txfContraseña.setText("jTextField1");

        btnIngresar.setBackground(new java.awt.Color(7, 134, 0, 215));
        btnIngresar.setRoundBottomLeft(10);
        btnIngresar.setRoundBottomRight(10);
        btnIngresar.setRoundTopLeft(10);
        btnIngresar.setRoundTopRight(10);
        btnIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIngresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIngresarMouseExited(evt);
            }
        });

        lblIngresar.setFont(new java.awt.Font("MS UI Gothic", 1, 30)); // NOI18N
        lblIngresar.setForeground(new java.awt.Color(255, 255, 255,240));
        lblIngresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIngresar.setText("ingresar");
        lblIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnIngresarLayout = new javax.swing.GroupLayout(btnIngresar);
        btnIngresar.setLayout(btnIngresarLayout);
        btnIngresarLayout.setHorizontalGroup(
            btnIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnIngresarLayout.setVerticalGroup(
            btnIngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIngresar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                .addGap(0, 55, Short.MAX_VALUE)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnIngresar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txfContraseña, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIngreseContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE))
                .addGap(45, 45, 45))
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblIngreseContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txfContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        add(pnlLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 590, 570, 380));

        lblImgCisco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/cisco (3).jpg"))); // NOI18N
        add(lblImgCisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 964));
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseEntered
        // TODO add your handling code here:
        btnIngresar.setBackground(colorIn);
        lblIngresar.setForeground(new java.awt.Color(153, 147, 147, 255));
        
    }//GEN-LAST:event_btnIngresarMouseEntered

    private void btnIngresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseExited
        // TODO add your handling code here:
        btnIngresar.setBackground(colorOut);
        lblIngresar.setForeground(new java.awt.Color(242, 242, 242, 255));
    }//GEN-LAST:event_btnIngresarMouseExited

    public void setReservacion(String alumno){
        colorIn = new java.awt.Color(25, 50, 178, 255);
        colorOut = new java.awt.Color(25, 50, 178, 215);
        pnlEstadoComputadora.setBackground(colorOut);
        pnlUsuarioReservado.setBackground(colorOut);
        btnIngresar.setBackground(colorOut);
        
        lblEstado.setText("equipo reservado");
        lblUsuarioReservado.setText("Bienvenido " + alumno); // aqui se cambiara cuando se defina el metodo que me regresa un nombre
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private presentacion.componentes.PanelRound btnIngresar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblImgCisco;
    private javax.swing.JLabel lblIngresar;
    private javax.swing.JLabel lblIngreseContraseña;
    private javax.swing.JLabel lblNumComputadora;
    private javax.swing.JLabel lblProgramaVersion;
    private javax.swing.JLabel lblUsuarioReservado;
    private presentacion.componentes.PanelRound pnlEstadoComputadora;
    private presentacion.componentes.PanelRound pnlLogin;
    private presentacion.componentes.PanelRound pnlNumComputadora;
    private javax.swing.JPanel pnlProgramaVersion;
    private presentacion.componentes.PanelRound pnlUsuarioReservado;
    private javax.swing.JTextField txfContraseña;
    // End of variables declaration//GEN-END:variables
}
