package presentacion_administrador.vistas;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author angel
 */
public class VentanaInicio extends javax.swing.JPanel {

    private JFrame frame;

    /**
     * Creates new form VentanaBienvenida
     *
     * @param frame
     */
    public VentanaInicio(JFrame frame) {
        initComponents();
        this.frame = frame;
        optBloqueos.setVisible(false);
        optComputadoras.setVisible(false);
        optLaboratorios.setVisible(false);
        optReportes.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNavegacion = new javax.swing.JPanel();
        btnComputadoras = new presentacion_administrador.componentes.BotonNavegador();
        lblComputadoras = new javax.swing.JLabel();
        btnBloqueos = new presentacion_administrador.componentes.BotonNavegador();
        lblAlumnos = new javax.swing.JLabel();
        btnLaboratorios = new presentacion_administrador.componentes.BotonNavegador();
        lblLaboratorios = new javax.swing.JLabel();
        btnReportes = new presentacion_administrador.componentes.BotonNavegador();
        lblReportes = new javax.swing.JLabel();
        optComputadoras = new javax.swing.JPanel();
        btnAgregarCompu = new presentacion_administrador.componentes.BotonNavegador();
        lblAgregarCompu = new javax.swing.JLabel();
        btnEliminarCompu = new presentacion_administrador.componentes.BotonNavegador();
        lblEliminarCompu = new javax.swing.JLabel();
        btnListarCompu = new presentacion_administrador.componentes.BotonNavegador();
        lblListarCompu = new javax.swing.JLabel();
        optBloqueos = new javax.swing.JPanel();
        btnBloquearAlumno = new presentacion_administrador.componentes.BotonNavegador();
        lblBloquearAlumno = new javax.swing.JLabel();
        btnDesbloquearAlumno = new presentacion_administrador.componentes.BotonNavegador();
        lblDesbloquearAlumno = new javax.swing.JLabel();
        btnListarBloqueos = new presentacion_administrador.componentes.BotonNavegador();
        listarBloqueos = new javax.swing.JLabel();
        optLaboratorios = new javax.swing.JPanel();
        btnAgregarLaboratorio = new presentacion_administrador.componentes.BotonNavegador();
        lblAgregarLaboratorio = new javax.swing.JLabel();
        btnModificarLaboratorio = new presentacion_administrador.componentes.BotonNavegador();
        lblModificarLaboratorio = new javax.swing.JLabel();
        btnListarLaboratorios = new presentacion_administrador.componentes.BotonNavegador();
        listarLaboratorios = new javax.swing.JLabel();
        optReportes = new javax.swing.JPanel();
        btnReporteCarreras = new presentacion_administrador.componentes.BotonNavegador();
        lblReporteCarreras = new javax.swing.JLabel();
        btnReporteBloqueos = new presentacion_administrador.componentes.BotonNavegador();
        lblReporteBloqueos = new javax.swing.JLabel();
        btnReporteCentros = new presentacion_administrador.componentes.BotonNavegador();
        lblReportesCentros = new javax.swing.JLabel();
        imgPrincipal = new javax.swing.JLabel();
        pnlInformacionOpciones = new javax.swing.JPanel();
        lblOpcionesComputadoras = new javax.swing.JLabel();
        lblOpcion1 = new javax.swing.JLabel();
        lblOpcion2 = new javax.swing.JLabel();
        lblOpcion3 = new javax.swing.JLabel();
        lblOpcionesAlumnos = new javax.swing.JLabel();
        lblOpcion4 = new javax.swing.JLabel();
        lblOpcion5 = new javax.swing.JLabel();
        lblOpcion6 = new javax.swing.JLabel();
        lblOpcionesLaboratorios = new javax.swing.JLabel();
        lblOpcion7 = new javax.swing.JLabel();
        lblOpcion8 = new javax.swing.JLabel();
        lblOpcion9 = new javax.swing.JLabel();
        lblOpcionesReportes = new javax.swing.JLabel();
        lblOpcion10 = new javax.swing.JLabel();
        lblOpcion11 = new javax.swing.JLabel();
        lblOpcion12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(16, 20, 65));
        setMinimumSize(new java.awt.Dimension(1440, 1024));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1440, 1024));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlNavegacion.setOpaque(false);
        pnlNavegacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnComputadoras.setBackground(new java.awt.Color(32, 39, 116));
        btnComputadoras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnComputadorasMouseClicked(evt);
            }
        });

        lblComputadoras.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        lblComputadoras.setForeground(new java.awt.Color(255, 255, 255));
        lblComputadoras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComputadoras.setText("computadoras");
        lblComputadoras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnComputadorasLayout = new javax.swing.GroupLayout(btnComputadoras);
        btnComputadoras.setLayout(btnComputadorasLayout);
        btnComputadorasLayout.setHorizontalGroup(
            btnComputadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnComputadorasLayout.createSequentialGroup()
                .addComponent(lblComputadoras, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnComputadorasLayout.setVerticalGroup(
            btnComputadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblComputadoras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlNavegacion.add(btnComputadoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 50));

        btnBloqueos.setBackground(new java.awt.Color(32, 39, 116));
        btnBloqueos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBloqueosMouseClicked(evt);
            }
        });

        lblAlumnos.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        lblAlumnos.setForeground(new java.awt.Color(255, 255, 255));
        lblAlumnos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAlumnos.setText("bloqueos");
        lblAlumnos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnBloqueosLayout = new javax.swing.GroupLayout(btnBloqueos);
        btnBloqueos.setLayout(btnBloqueosLayout);
        btnBloqueosLayout.setHorizontalGroup(
            btnBloqueosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );
        btnBloqueosLayout.setVerticalGroup(
            btnBloqueosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAlumnos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlNavegacion.add(btnBloqueos, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 360, 50));

        btnLaboratorios.setBackground(new java.awt.Color(32, 39, 116));
        btnLaboratorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLaboratoriosMouseClicked(evt);
            }
        });

        lblLaboratorios.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        lblLaboratorios.setForeground(new java.awt.Color(255, 255, 255));
        lblLaboratorios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLaboratorios.setText("laboratorios");
        lblLaboratorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnLaboratoriosLayout = new javax.swing.GroupLayout(btnLaboratorios);
        btnLaboratorios.setLayout(btnLaboratoriosLayout);
        btnLaboratoriosLayout.setHorizontalGroup(
            btnLaboratoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLaboratorios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );
        btnLaboratoriosLayout.setVerticalGroup(
            btnLaboratoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLaboratorios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlNavegacion.add(btnLaboratorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 360, 50));

        btnReportes.setBackground(new java.awt.Color(32, 39, 116));
        btnReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReportesMouseClicked(evt);
            }
        });

        lblReportes.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        lblReportes.setForeground(new java.awt.Color(255, 255, 255));
        lblReportes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReportes.setText("reportes");
        lblReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnReportesLayout = new javax.swing.GroupLayout(btnReportes);
        btnReportes.setLayout(btnReportesLayout);
        btnReportesLayout.setHorizontalGroup(
            btnReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblReportes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );
        btnReportesLayout.setVerticalGroup(
            btnReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblReportes, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlNavegacion.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 0, 360, 50));

        add(pnlNavegacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 50));

        optComputadoras.setBackground(new java.awt.Color(32, 39, 116));
        optComputadoras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregarCompu.setBackground(new java.awt.Color(32, 39, 116));
        btnAgregarCompu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarCompuMouseClicked(evt);
            }
        });

        lblAgregarCompu.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        lblAgregarCompu.setForeground(new java.awt.Color(255, 255, 255));
        lblAgregarCompu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgregarCompu.setText("agregar computadora");
        lblAgregarCompu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnAgregarCompuLayout = new javax.swing.GroupLayout(btnAgregarCompu);
        btnAgregarCompu.setLayout(btnAgregarCompuLayout);
        btnAgregarCompuLayout.setHorizontalGroup(
            btnAgregarCompuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAgregarCompu, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        btnAgregarCompuLayout.setVerticalGroup(
            btnAgregarCompuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAgregarCompu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        optComputadoras.add(btnAgregarCompu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 50));

        btnEliminarCompu.setBackground(new java.awt.Color(32, 39, 116));
        btnEliminarCompu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarCompuMouseClicked(evt);
            }
        });

        lblEliminarCompu.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        lblEliminarCompu.setForeground(new java.awt.Color(255, 255, 255));
        lblEliminarCompu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEliminarCompu.setText("eliminar computadora");
        lblEliminarCompu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnEliminarCompuLayout = new javax.swing.GroupLayout(btnEliminarCompu);
        btnEliminarCompu.setLayout(btnEliminarCompuLayout);
        btnEliminarCompuLayout.setHorizontalGroup(
            btnEliminarCompuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEliminarCompu, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        btnEliminarCompuLayout.setVerticalGroup(
            btnEliminarCompuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEliminarCompu, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        optComputadoras.add(btnEliminarCompu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 340, 50));

        btnListarCompu.setBackground(new java.awt.Color(32, 39, 116));
        btnListarCompu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListarCompuMouseClicked(evt);
            }
        });

        lblListarCompu.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        lblListarCompu.setForeground(new java.awt.Color(255, 255, 255));
        lblListarCompu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblListarCompu.setText("listar computadora");
        lblListarCompu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnListarCompuLayout = new javax.swing.GroupLayout(btnListarCompu);
        btnListarCompu.setLayout(btnListarCompuLayout);
        btnListarCompuLayout.setHorizontalGroup(
            btnListarCompuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblListarCompu, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        btnListarCompuLayout.setVerticalGroup(
            btnListarCompuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblListarCompu, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        optComputadoras.add(btnListarCompu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 340, 40));

        add(optComputadoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 340, 160));

        optBloqueos.setBackground(new java.awt.Color(32, 39, 116));
        optBloqueos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBloquearAlumno.setBackground(new java.awt.Color(32, 39, 116));
        btnBloquearAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBloquearAlumnoMouseClicked(evt);
            }
        });

        lblBloquearAlumno.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        lblBloquearAlumno.setForeground(new java.awt.Color(255, 255, 255));
        lblBloquearAlumno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBloquearAlumno.setText("bloquear alumno");
        lblBloquearAlumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnBloquearAlumnoLayout = new javax.swing.GroupLayout(btnBloquearAlumno);
        btnBloquearAlumno.setLayout(btnBloquearAlumnoLayout);
        btnBloquearAlumnoLayout.setHorizontalGroup(
            btnBloquearAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBloquearAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        btnBloquearAlumnoLayout.setVerticalGroup(
            btnBloquearAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBloquearAlumno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        optBloqueos.add(btnBloquearAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 50));

        btnDesbloquearAlumno.setBackground(new java.awt.Color(32, 39, 116));
        btnDesbloquearAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDesbloquearAlumnoMouseClicked(evt);
            }
        });

        lblDesbloquearAlumno.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        lblDesbloquearAlumno.setForeground(new java.awt.Color(255, 255, 255));
        lblDesbloquearAlumno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDesbloquearAlumno.setText("desbloquear alumno");
        lblDesbloquearAlumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnDesbloquearAlumnoLayout = new javax.swing.GroupLayout(btnDesbloquearAlumno);
        btnDesbloquearAlumno.setLayout(btnDesbloquearAlumnoLayout);
        btnDesbloquearAlumnoLayout.setHorizontalGroup(
            btnDesbloquearAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDesbloquearAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        btnDesbloquearAlumnoLayout.setVerticalGroup(
            btnDesbloquearAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDesbloquearAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        optBloqueos.add(btnDesbloquearAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 340, 50));

        btnListarBloqueos.setBackground(new java.awt.Color(32, 39, 116));
        btnListarBloqueos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListarBloqueosMouseClicked(evt);
            }
        });

        listarBloqueos.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        listarBloqueos.setForeground(new java.awt.Color(255, 255, 255));
        listarBloqueos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listarBloqueos.setText("listar bloqueos");
        listarBloqueos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnListarBloqueosLayout = new javax.swing.GroupLayout(btnListarBloqueos);
        btnListarBloqueos.setLayout(btnListarBloqueosLayout);
        btnListarBloqueosLayout.setHorizontalGroup(
            btnListarBloqueosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listarBloqueos, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        btnListarBloqueosLayout.setVerticalGroup(
            btnListarBloqueosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listarBloqueos, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        optBloqueos.add(btnListarBloqueos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 340, 40));

        add(optBloqueos, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 340, 160));

        optLaboratorios.setBackground(new java.awt.Color(32, 39, 116));
        optLaboratorios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregarLaboratorio.setBackground(new java.awt.Color(32, 39, 116));
        btnAgregarLaboratorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarLaboratorioMouseClicked(evt);
            }
        });

        lblAgregarLaboratorio.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        lblAgregarLaboratorio.setForeground(new java.awt.Color(255, 255, 255));
        lblAgregarLaboratorio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgregarLaboratorio.setText("agregar laboratorio");
        lblAgregarLaboratorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnAgregarLaboratorioLayout = new javax.swing.GroupLayout(btnAgregarLaboratorio);
        btnAgregarLaboratorio.setLayout(btnAgregarLaboratorioLayout);
        btnAgregarLaboratorioLayout.setHorizontalGroup(
            btnAgregarLaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAgregarLaboratorio, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        btnAgregarLaboratorioLayout.setVerticalGroup(
            btnAgregarLaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAgregarLaboratorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        optLaboratorios.add(btnAgregarLaboratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 50));

        btnModificarLaboratorio.setBackground(new java.awt.Color(32, 39, 116));
        btnModificarLaboratorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarLaboratorioMouseClicked(evt);
            }
        });

        lblModificarLaboratorio.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        lblModificarLaboratorio.setForeground(new java.awt.Color(255, 255, 255));
        lblModificarLaboratorio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModificarLaboratorio.setText("modificar laboratorio");
        lblModificarLaboratorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnModificarLaboratorioLayout = new javax.swing.GroupLayout(btnModificarLaboratorio);
        btnModificarLaboratorio.setLayout(btnModificarLaboratorioLayout);
        btnModificarLaboratorioLayout.setHorizontalGroup(
            btnModificarLaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblModificarLaboratorio, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        btnModificarLaboratorioLayout.setVerticalGroup(
            btnModificarLaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblModificarLaboratorio, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        optLaboratorios.add(btnModificarLaboratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 340, 50));

        btnListarLaboratorios.setBackground(new java.awt.Color(32, 39, 116));
        btnListarLaboratorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListarLaboratoriosMouseClicked(evt);
            }
        });

        listarLaboratorios.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        listarLaboratorios.setForeground(new java.awt.Color(255, 255, 255));
        listarLaboratorios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listarLaboratorios.setText("listar laboratorios");
        listarLaboratorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnListarLaboratoriosLayout = new javax.swing.GroupLayout(btnListarLaboratorios);
        btnListarLaboratorios.setLayout(btnListarLaboratoriosLayout);
        btnListarLaboratoriosLayout.setHorizontalGroup(
            btnListarLaboratoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listarLaboratorios, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        btnListarLaboratoriosLayout.setVerticalGroup(
            btnListarLaboratoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listarLaboratorios, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        optLaboratorios.add(btnListarLaboratorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 340, 40));

        add(optLaboratorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 50, 340, 160));

        optReportes.setBackground(new java.awt.Color(32, 39, 116));
        optReportes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnReporteCarreras.setBackground(new java.awt.Color(32, 39, 116));
        btnReporteCarreras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReporteCarrerasMouseClicked(evt);
            }
        });

        lblReporteCarreras.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        lblReporteCarreras.setForeground(new java.awt.Color(255, 255, 255));
        lblReporteCarreras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReporteCarreras.setText("reporte carreras");
        lblReporteCarreras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnReporteCarrerasLayout = new javax.swing.GroupLayout(btnReporteCarreras);
        btnReporteCarreras.setLayout(btnReporteCarrerasLayout);
        btnReporteCarrerasLayout.setHorizontalGroup(
            btnReporteCarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblReporteCarreras, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        btnReporteCarrerasLayout.setVerticalGroup(
            btnReporteCarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblReporteCarreras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        optReportes.add(btnReporteCarreras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 50));

        btnReporteBloqueos.setBackground(new java.awt.Color(32, 39, 116));
        btnReporteBloqueos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReporteBloqueosMouseClicked(evt);
            }
        });

        lblReporteBloqueos.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        lblReporteBloqueos.setForeground(new java.awt.Color(255, 255, 255));
        lblReporteBloqueos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReporteBloqueos.setText("reporte bloqueos");
        lblReporteBloqueos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnReporteBloqueosLayout = new javax.swing.GroupLayout(btnReporteBloqueos);
        btnReporteBloqueos.setLayout(btnReporteBloqueosLayout);
        btnReporteBloqueosLayout.setHorizontalGroup(
            btnReporteBloqueosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblReporteBloqueos, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        btnReporteBloqueosLayout.setVerticalGroup(
            btnReporteBloqueosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblReporteBloqueos, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        optReportes.add(btnReporteBloqueos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 340, 50));

        btnReporteCentros.setBackground(new java.awt.Color(32, 39, 116));
        btnReporteCentros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReporteCentrosMouseClicked(evt);
            }
        });

        lblReportesCentros.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        lblReportesCentros.setForeground(new java.awt.Color(255, 255, 255));
        lblReportesCentros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReportesCentros.setText("reporte centros");
        lblReportesCentros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnReporteCentrosLayout = new javax.swing.GroupLayout(btnReporteCentros);
        btnReporteCentros.setLayout(btnReporteCentrosLayout);
        btnReporteCentrosLayout.setHorizontalGroup(
            btnReporteCentrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblReportesCentros, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        btnReporteCentrosLayout.setVerticalGroup(
            btnReporteCentrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblReportesCentros, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        optReportes.add(btnReporteCentros, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 340, 40));

        add(optReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 50, 340, 160));

        imgPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        imgPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentacion/imagenes/itson_baner (2).jpg"))); // NOI18N
        add(imgPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 96, 1340, 290));

        pnlInformacionOpciones.setBackground(new java.awt.Color(25, 30, 69));
        pnlInformacionOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOpcionesComputadoras.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        lblOpcionesComputadoras.setForeground(new java.awt.Color(255, 255, 255));
        lblOpcionesComputadoras.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblOpcionesComputadoras.setText("OPCIONES DE COMPUTADORAS");
        pnlInformacionOpciones.add(lblOpcionesComputadoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 6, 1290, 40));

        lblOpcion1.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        lblOpcion1.setForeground(new java.awt.Color(255, 255, 255));
        lblOpcion1.setText("COMPUTADORAS > AGREGAR COMPUTADORA");
        pnlInformacionOpciones.add(lblOpcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 46, 1240, 30));

        lblOpcion2.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        lblOpcion2.setForeground(new java.awt.Color(255, 255, 255));
        lblOpcion2.setText("COMPUTADORAS > ELIMINAR COMPUTADORA");
        pnlInformacionOpciones.add(lblOpcion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 76, 1240, 30));

        lblOpcion3.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        lblOpcion3.setForeground(new java.awt.Color(255, 255, 255));
        lblOpcion3.setText("COMPUTADORAS > LISTAR COMPUTADORA");
        pnlInformacionOpciones.add(lblOpcion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 106, 1240, 30));

        lblOpcionesAlumnos.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        lblOpcionesAlumnos.setForeground(new java.awt.Color(255, 255, 255));
        lblOpcionesAlumnos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblOpcionesAlumnos.setText("OPCIONES DE ALUMNOS");
        pnlInformacionOpciones.add(lblOpcionesAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 156, 1290, 30));

        lblOpcion4.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        lblOpcion4.setForeground(new java.awt.Color(255, 255, 255));
        lblOpcion4.setText("ALUMNOS > BLOQUEAR ALUMNO");
        pnlInformacionOpciones.add(lblOpcion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 186, 1240, 30));

        lblOpcion5.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        lblOpcion5.setForeground(new java.awt.Color(255, 255, 255));
        lblOpcion5.setText("ALUMNOS > DESBLOQUEAR ALUMNO");
        pnlInformacionOpciones.add(lblOpcion5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 216, 1240, 20));

        lblOpcion6.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        lblOpcion6.setForeground(new java.awt.Color(255, 255, 255));
        lblOpcion6.setText("ALUMNOS > LISTAR ALUMNOS");
        pnlInformacionOpciones.add(lblOpcion6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 236, 1240, 30));

        lblOpcionesLaboratorios.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        lblOpcionesLaboratorios.setForeground(new java.awt.Color(255, 255, 255));
        lblOpcionesLaboratorios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblOpcionesLaboratorios.setText("OPCIONES DE LABORATORIOS");
        pnlInformacionOpciones.add(lblOpcionesLaboratorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 286, 1290, 30));

        lblOpcion7.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        lblOpcion7.setForeground(new java.awt.Color(255, 255, 255));
        lblOpcion7.setText("LABORATORIOS > AGREGAR LABORATORIO");
        pnlInformacionOpciones.add(lblOpcion7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 326, 1240, 30));

        lblOpcion8.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        lblOpcion8.setForeground(new java.awt.Color(255, 255, 255));
        lblOpcion8.setText("LABORATORIOS > MODIFICAR LABORATORIO");
        pnlInformacionOpciones.add(lblOpcion8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 356, 1240, 20));

        lblOpcion9.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        lblOpcion9.setForeground(new java.awt.Color(255, 255, 255));
        lblOpcion9.setText("LABORATORIOS > LISTAR LABORATORIOS");
        pnlInformacionOpciones.add(lblOpcion9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 376, 1240, 30));

        lblOpcionesReportes.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        lblOpcionesReportes.setForeground(new java.awt.Color(255, 255, 255));
        lblOpcionesReportes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblOpcionesReportes.setText("OPCIONES DE REPORTES");
        pnlInformacionOpciones.add(lblOpcionesReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 416, 1290, 30));

        lblOpcion10.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        lblOpcion10.setForeground(new java.awt.Color(255, 255, 255));
        lblOpcion10.setText("REPORTES > REPORTE CARRERAS");
        pnlInformacionOpciones.add(lblOpcion10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 456, 1240, 30));

        lblOpcion11.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        lblOpcion11.setForeground(new java.awt.Color(255, 255, 255));
        lblOpcion11.setText("REPORTES > REPORTE BLOQUEOS");
        pnlInformacionOpciones.add(lblOpcion11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 486, 1240, 20));

        lblOpcion12.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        lblOpcion12.setForeground(new java.awt.Color(255, 255, 255));
        lblOpcion12.setText("REPORTES > REPORTE CENTROS");
        pnlInformacionOpciones.add(lblOpcion12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 506, 1240, 30));

        add(pnlInformacionOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 1340, 640));
    }// </editor-fold>//GEN-END:initComponents

    private void btnComputadorasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComputadorasMouseClicked
        // TODO add your handling code here:
        SwingUtilities.invokeLater(() -> {
            optComputadoras.setVisible(!optComputadoras.isVisible());
        });
    }//GEN-LAST:event_btnComputadorasMouseClicked

    private void btnBloqueosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBloqueosMouseClicked
        // TODO add your handling code here:
        SwingUtilities.invokeLater(() -> {
            optBloqueos.setVisible(!optBloqueos.isVisible());
        });
    }//GEN-LAST:event_btnBloqueosMouseClicked

    private void btnLaboratoriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaboratoriosMouseClicked
        // TODO add your handling code here:
        SwingUtilities.invokeLater(() -> {
            optLaboratorios.setVisible(!optLaboratorios.isVisible());
        });
    }//GEN-LAST:event_btnLaboratoriosMouseClicked

    private void btnReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesMouseClicked
        // TODO add your handling code here:
        SwingUtilities.invokeLater(() -> {
            optReportes.setVisible(!optReportes.isVisible());
        });
    }//GEN-LAST:event_btnReportesMouseClicked

    
    private void btnEliminarCompuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarCompuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarCompuMouseClicked

    private void btnAgregarCompuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarCompuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarCompuMouseClicked

    private void btnListarCompuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarCompuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListarCompuMouseClicked

    private void btnBloquearAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBloquearAlumnoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBloquearAlumnoMouseClicked

    private void btnDesbloquearAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDesbloquearAlumnoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDesbloquearAlumnoMouseClicked

    private void btnListarBloqueosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarBloqueosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListarBloqueosMouseClicked

    private void btnAgregarLaboratorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarLaboratorioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarLaboratorioMouseClicked

    private void btnModificarLaboratorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarLaboratorioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarLaboratorioMouseClicked

    private void btnListarLaboratoriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarLaboratoriosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListarLaboratoriosMouseClicked

    private void btnReporteCarrerasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteCarrerasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReporteCarrerasMouseClicked

    private void btnReporteBloqueosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteBloqueosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReporteBloqueosMouseClicked

    private void btnReporteCentrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteCentrosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReporteCentrosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAgregarCompu;
    private javax.swing.JPanel btnAgregarLaboratorio;
    private javax.swing.JPanel btnBloquearAlumno;
    private javax.swing.JPanel btnBloqueos;
    private javax.swing.JPanel btnComputadoras;
    private javax.swing.JPanel btnDesbloquearAlumno;
    private javax.swing.JPanel btnEliminarCompu;
    private javax.swing.JPanel btnLaboratorios;
    private javax.swing.JPanel btnListarBloqueos;
    private javax.swing.JPanel btnListarCompu;
    private javax.swing.JPanel btnListarLaboratorios;
    private javax.swing.JPanel btnModificarLaboratorio;
    private javax.swing.JPanel btnReporteBloqueos;
    private javax.swing.JPanel btnReporteCarreras;
    private javax.swing.JPanel btnReporteCentros;
    private javax.swing.JPanel btnReportes;
    private javax.swing.JLabel imgPrincipal;
    private javax.swing.JLabel lblAgregarCompu;
    private javax.swing.JLabel lblAgregarLaboratorio;
    private javax.swing.JLabel lblAlumnos;
    private javax.swing.JLabel lblBloquearAlumno;
    private javax.swing.JLabel lblComputadoras;
    private javax.swing.JLabel lblDesbloquearAlumno;
    private javax.swing.JLabel lblEliminarCompu;
    private javax.swing.JLabel lblLaboratorios;
    private javax.swing.JLabel lblListarCompu;
    private javax.swing.JLabel lblModificarLaboratorio;
    private javax.swing.JLabel lblOpcion1;
    private javax.swing.JLabel lblOpcion10;
    private javax.swing.JLabel lblOpcion11;
    private javax.swing.JLabel lblOpcion12;
    private javax.swing.JLabel lblOpcion2;
    private javax.swing.JLabel lblOpcion3;
    private javax.swing.JLabel lblOpcion4;
    private javax.swing.JLabel lblOpcion5;
    private javax.swing.JLabel lblOpcion6;
    private javax.swing.JLabel lblOpcion7;
    private javax.swing.JLabel lblOpcion8;
    private javax.swing.JLabel lblOpcion9;
    private javax.swing.JLabel lblOpcionesAlumnos;
    private javax.swing.JLabel lblOpcionesComputadoras;
    private javax.swing.JLabel lblOpcionesLaboratorios;
    private javax.swing.JLabel lblOpcionesReportes;
    private javax.swing.JLabel lblReporteBloqueos;
    private javax.swing.JLabel lblReporteCarreras;
    private javax.swing.JLabel lblReportes;
    private javax.swing.JLabel lblReportesCentros;
    private javax.swing.JLabel listarBloqueos;
    private javax.swing.JLabel listarLaboratorios;
    private javax.swing.JPanel optBloqueos;
    private javax.swing.JPanel optComputadoras;
    private javax.swing.JPanel optLaboratorios;
    private javax.swing.JPanel optReportes;
    private javax.swing.JPanel pnlInformacionOpciones;
    private javax.swing.JPanel pnlNavegacion;
    // End of variables declaration//GEN-END:variables
}
