
package presentacion_bloqueo.vistas;

/**
 * 
 * @author erwbyel
 */
public class VentanaIlegal extends javax.swing.JPanel {

    /**
     * Creates new form VentanaIlegal
     */
    public VentanaIlegal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMensaje = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblMensaje = new javax.swing.JLabel();
        btnCerrar = new presentacion_bloqueo.componentes.PanelRound();
        lblCerrar = new javax.swing.JLabel();
        btnReintentar = new presentacion_bloqueo.componentes.PanelRound();
        lblReintentar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(1440, 1024));
        setPreferredSize(new java.awt.Dimension(1440, 1024));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMensaje.setBackground(new java.awt.Color(16, 20, 65));

        lblTitulo.setFont(new java.awt.Font("MS UI Gothic", 1, 30)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("SU DISPOSITIVO NO ESTA AUTORIZADO PARA CORRER EL PROGRAMA");

        lblMensaje.setFont(new java.awt.Font("MS UI Gothic", 1, 25)); // NOI18N
        lblMensaje.setForeground(new java.awt.Color(255, 255, 255));
        lblMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensaje.setText("CONTACTE AL TECNICO DEL LABORATORIO");

        btnCerrar.setBackground(new java.awt.Color(212, 82, 82));
        btnCerrar.setRoundBottomLeft(10);
        btnCerrar.setRoundBottomRight(10);
        btnCerrar.setRoundTopLeft(10);
        btnCerrar.setRoundTopRight(10);

        lblCerrar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblCerrar.setForeground(new java.awt.Color(255, 255, 255));
        lblCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCerrar.setText("CERRAR PROGRAMA");
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCerrarLayout = new javax.swing.GroupLayout(btnCerrar);
        btnCerrar.setLayout(btnCerrarLayout);
        btnCerrarLayout.setHorizontalGroup(
            btnCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
        );
        btnCerrarLayout.setVerticalGroup(
            btnCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnReintentar.setBackground(new java.awt.Color(25, 50, 178));
        btnReintentar.setRoundBottomLeft(10);
        btnReintentar.setRoundBottomRight(10);
        btnReintentar.setRoundTopLeft(10);
        btnReintentar.setRoundTopRight(10);

        lblReintentar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblReintentar.setForeground(new java.awt.Color(255, 255, 255));
        lblReintentar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReintentar.setText("REINTENTAR");
        lblReintentar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblReintentar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReintentarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblReintentarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblReintentarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnReintentarLayout = new javax.swing.GroupLayout(btnReintentar);
        btnReintentar.setLayout(btnReintentarLayout);
        btnReintentarLayout.setHorizontalGroup(
            btnReintentarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblReintentar, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
        );
        btnReintentarLayout.setVerticalGroup(
            btnReintentarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblReintentar, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlMensajeLayout = new javax.swing.GroupLayout(pnlMensaje);
        pnlMensaje.setLayout(pnlMensajeLayout);
        pnlMensajeLayout.setHorizontalGroup(
            pnlMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMensajeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 1428, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pnlMensajeLayout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172)
                .addComponent(btnReintentar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMensajeLayout.setVerticalGroup(
            pnlMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMensajeLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(lblMensaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addGroup(pnlMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReintentar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(103, 103, 103))
        );

        add(pnlMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 234, 1440, 440));
    }// </editor-fold>//GEN-END:initComponents

    private void lblCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseEntered
        // TODO add your handling code here:
        btnCerrar.setBackground(new java.awt.Color(200, 46, 46));
    }//GEN-LAST:event_lblCerrarMouseEntered

    private void lblCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseExited
        // TODO add your handling code here:
        btnCerrar.setBackground(new java.awt.Color(212, 82, 82));
    }//GEN-LAST:event_lblCerrarMouseExited

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        // TODO add your handling code here:
        presentacion_bloqueo.Controlador.cerrarPrograma();
    }//GEN-LAST:event_lblCerrarMouseClicked

    
    
    private void lblReintentarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReintentarMouseEntered
        // TODO add your handling code here:
        btnReintentar.setBackground(new java.awt.Color(4, 40, 215));
    }//GEN-LAST:event_lblReintentarMouseEntered

    private void lblReintentarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReintentarMouseExited
        // TODO add your handling code here:
        btnReintentar.setBackground(new java.awt.Color(25, 50, 178));
    }//GEN-LAST:event_lblReintentarMouseExited

    private void lblReintentarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReintentarMouseClicked
        // TODO add your handling code here:
        //aqui se vuelve a llamar a control para revalidar
    }//GEN-LAST:event_lblReintentarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private presentacion_bloqueo.componentes.PanelRound btnCerrar;
    private presentacion_bloqueo.componentes.PanelRound btnReintentar;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblReintentar;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlMensaje;
    // End of variables declaration//GEN-END:variables
}
