package presentacion_administrador.vistas.computadoras.agregar_computadora;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import presentacion_administrador.componentes.PanelNavegacion;

/**
 *
 * @author erwbyel
 */
public class VentanaComputadoraAgrega extends javax.swing.JPanel {

    private JFrame frame;

    /**
     * Creates new form VentanaBienvenida
     *
     * @param frame
     */
    public VentanaComputadoraAgrega(JFrame frame) {
        this.frame = frame;
        initComponents();
        PanelNavegacion pnlNavegacion = new PanelNavegacion(frame);
        add(pnlNavegacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 200));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBarraProceso = new presentacion_administrador.componentes.PanelRound();
        pnlUno = new presentacion_administrador.componentes.PanelRound();
        lblUno = new javax.swing.JLabel();
        pnlDos = new presentacion_administrador.componentes.PanelRound();
        lblDos = new javax.swing.JLabel();
        pnlTres = new presentacion_administrador.componentes.PanelRound();
        lblTres = new javax.swing.JLabel();
        separadorUnoDos = new javax.swing.JPanel();
        separadorDosTres = new javax.swing.JPanel();
        pnlTituloOperacion = new presentacion_administrador.componentes.PanelRound();
        lblTituloOperacion = new javax.swing.JLabel();
        pnlContenidoOperacion = new presentacion_administrador.componentes.PanelRound();
        pnlEntradaLaboratorio = new presentacion_administrador.componentes.PanelRound();
        lblLaboratorio = new javax.swing.JLabel();
        pnlSeleccionLaboratorio = new presentacion_administrador.componentes.PanelRound();
        lblSeleccionLaboratorio = new javax.swing.JLabel();
        pnlEntradaIp = new presentacion_administrador.componentes.PanelRound();
        lblIp = new javax.swing.JLabel();
        txfIp = new javax.swing.JTextField();
        pnlEntradaNumero = new presentacion_administrador.componentes.PanelRound();
        lblNumero = new javax.swing.JLabel();
        txfNumero = new javax.swing.JTextField();
        pnlEntradaTipo = new presentacion_administrador.componentes.PanelRound();
        lblTipo = new javax.swing.JLabel();
        pnlSeleccionTipo = new presentacion_administrador.componentes.PanelRound();
        lblSeleccionTipo = new javax.swing.JLabel();
        lblCancelar = new javax.swing.JLabel();
        botonCancelar = new presentacion_administrador.componentes.BotonCancelar();
        lblContinuar = new javax.swing.JLabel();
        botonContinuar = new presentacion_administrador.componentes.BotonSiguiente();

        setBackground(new java.awt.Color(16, 20, 65));
        setMinimumSize(new java.awt.Dimension(1440, 1024));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1440, 1024));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBarraProceso.setBackground(new java.awt.Color(32, 39, 116));
        pnlBarraProceso.setRoundTopLeft(15);
        pnlBarraProceso.setRoundTopRight(15);
        pnlBarraProceso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlUno.setBackground(new java.awt.Color(25, 50, 178));
        pnlUno.setRoundBottomLeft(200);
        pnlUno.setRoundBottomRight(200);
        pnlUno.setRoundTopLeft(200);
        pnlUno.setRoundTopRight(200);

        lblUno.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblUno.setForeground(new java.awt.Color(255, 255, 255));
        lblUno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUno.setText("1");

        javax.swing.GroupLayout pnlUnoLayout = new javax.swing.GroupLayout(pnlUno);
        pnlUno.setLayout(pnlUnoLayout);
        pnlUnoLayout.setHorizontalGroup(
            pnlUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUno, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        pnlUnoLayout.setVerticalGroup(
            pnlUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUno, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlBarraProceso.add(pnlUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, 50));

        pnlDos.setBackground(new java.awt.Color(105, 111, 153));
        pnlDos.setRoundBottomLeft(200);
        pnlDos.setRoundBottomRight(200);
        pnlDos.setRoundTopLeft(200);
        pnlDos.setRoundTopRight(200);

        lblDos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDos.setForeground(new java.awt.Color(255, 255, 255));
        lblDos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDos.setText("2");

        javax.swing.GroupLayout pnlDosLayout = new javax.swing.GroupLayout(pnlDos);
        pnlDos.setLayout(pnlDosLayout);
        pnlDosLayout.setHorizontalGroup(
            pnlDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDos, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        pnlDosLayout.setVerticalGroup(
            pnlDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDos, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlBarraProceso.add(pnlDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 50, 50));

        pnlTres.setBackground(new java.awt.Color(105, 111, 153));
        pnlTres.setRoundBottomLeft(200);
        pnlTres.setRoundBottomRight(200);
        pnlTres.setRoundTopLeft(200);
        pnlTres.setRoundTopRight(200);

        lblTres.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTres.setForeground(new java.awt.Color(255, 255, 255));
        lblTres.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTres.setText("3");

        javax.swing.GroupLayout pnlTresLayout = new javax.swing.GroupLayout(pnlTres);
        pnlTres.setLayout(pnlTresLayout);
        pnlTresLayout.setHorizontalGroup(
            pnlTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTres, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        pnlTresLayout.setVerticalGroup(
            pnlTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTres, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlBarraProceso.add(pnlTres, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 50, 50));

        separadorUnoDos.setBackground(new java.awt.Color(105, 111, 153));

        javax.swing.GroupLayout separadorUnoDosLayout = new javax.swing.GroupLayout(separadorUnoDos);
        separadorUnoDos.setLayout(separadorUnoDosLayout);
        separadorUnoDosLayout.setHorizontalGroup(
            separadorUnoDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        separadorUnoDosLayout.setVerticalGroup(
            separadorUnoDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlBarraProceso.add(separadorUnoDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 90, -1));

        separadorDosTres.setBackground(new java.awt.Color(105, 111, 153));

        javax.swing.GroupLayout separadorDosTresLayout = new javax.swing.GroupLayout(separadorDosTres);
        separadorDosTres.setLayout(separadorDosTresLayout);
        separadorDosTresLayout.setHorizontalGroup(
            separadorDosTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        separadorDosTresLayout.setVerticalGroup(
            separadorDosTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlBarraProceso.add(separadorDosTres, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 90, -1));

        add(pnlBarraProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 190, 330, 70));

        pnlTituloOperacion.setBackground(new java.awt.Color(105, 111, 153));
        pnlTituloOperacion.setRoundTopLeft(20);
        pnlTituloOperacion.setRoundTopRight(20);

        lblTituloOperacion.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        lblTituloOperacion.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloOperacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloOperacion.setText("agregar computadora");
        lblTituloOperacion.setToolTipText("");
        lblTituloOperacion.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout pnlTituloOperacionLayout = new javax.swing.GroupLayout(pnlTituloOperacion);
        pnlTituloOperacion.setLayout(pnlTituloOperacionLayout);
        pnlTituloOperacionLayout.setHorizontalGroup(
            pnlTituloOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTituloOperacion, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );
        pnlTituloOperacionLayout.setVerticalGroup(
            pnlTituloOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTituloOperacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        add(pnlTituloOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 620, 50));

        pnlContenidoOperacion.setBackground(new java.awt.Color(25, 30, 69));
        pnlContenidoOperacion.setRoundBottomLeft(20);
        pnlContenidoOperacion.setRoundBottomRight(20);

        pnlEntradaLaboratorio.setBackground(new java.awt.Color(98, 102, 141));
        pnlEntradaLaboratorio.setRoundBottomLeft(15);
        pnlEntradaLaboratorio.setRoundBottomRight(15);
        pnlEntradaLaboratorio.setRoundTopLeft(15);
        pnlEntradaLaboratorio.setRoundTopRight(15);

        lblLaboratorio.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        lblLaboratorio.setForeground(new java.awt.Color(255, 255, 255));
        lblLaboratorio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLaboratorio.setText("laboratorio");
        lblLaboratorio.setToolTipText("");

        pnlSeleccionLaboratorio.setBackground(new java.awt.Color(32, 39, 116));
        pnlSeleccionLaboratorio.setRoundBottomLeft(10);
        pnlSeleccionLaboratorio.setRoundBottomRight(10);
        pnlSeleccionLaboratorio.setRoundTopLeft(10);
        pnlSeleccionLaboratorio.setRoundTopRight(10);

        lblSeleccionLaboratorio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSeleccionLaboratorio.setForeground(new java.awt.Color(255, 255, 255));
        lblSeleccionLaboratorio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeleccionLaboratorio.setText("-- seleccione el laboratorio --");
        lblSeleccionLaboratorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnlSeleccionLaboratorioLayout = new javax.swing.GroupLayout(pnlSeleccionLaboratorio);
        pnlSeleccionLaboratorio.setLayout(pnlSeleccionLaboratorioLayout);
        pnlSeleccionLaboratorioLayout.setHorizontalGroup(
            pnlSeleccionLaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSeleccionLaboratorio, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
        );
        pnlSeleccionLaboratorioLayout.setVerticalGroup(
            pnlSeleccionLaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSeleccionLaboratorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlEntradaLaboratorioLayout = new javax.swing.GroupLayout(pnlEntradaLaboratorio);
        pnlEntradaLaboratorio.setLayout(pnlEntradaLaboratorioLayout);
        pnlEntradaLaboratorioLayout.setHorizontalGroup(
            pnlEntradaLaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEntradaLaboratorioLayout.createSequentialGroup()
                .addComponent(lblLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(pnlSeleccionLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlEntradaLaboratorioLayout.setVerticalGroup(
            pnlEntradaLaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEntradaLaboratorioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEntradaLaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLaboratorio, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(pnlSeleccionLaboratorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlEntradaIp.setBackground(new java.awt.Color(98, 102, 141));
        pnlEntradaIp.setRoundBottomLeft(15);
        pnlEntradaIp.setRoundBottomRight(15);
        pnlEntradaIp.setRoundTopLeft(15);
        pnlEntradaIp.setRoundTopRight(15);

        lblIp.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        lblIp.setForeground(new java.awt.Color(255, 255, 255));
        lblIp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIp.setText("IP");
        lblIp.setToolTipText("");

        txfIp.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txfIp.setForeground(new java.awt.Color(153, 153, 153));
        txfIp.setText("  ingrese la ip de la computadora");
        txfIp.setBorder(null);

        javax.swing.GroupLayout pnlEntradaIpLayout = new javax.swing.GroupLayout(pnlEntradaIp);
        pnlEntradaIp.setLayout(pnlEntradaIpLayout);
        pnlEntradaIpLayout.setHorizontalGroup(
            pnlEntradaIpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEntradaIpLayout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(txfIp, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlEntradaIpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlEntradaIpLayout.createSequentialGroup()
                    .addComponent(lblIp, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 636, Short.MAX_VALUE)))
        );
        pnlEntradaIpLayout.setVerticalGroup(
            pnlEntradaIpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEntradaIpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txfIp, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlEntradaIpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlEntradaIpLayout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(lblIp, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addGap(8, 8, 8)))
        );

        pnlEntradaNumero.setBackground(new java.awt.Color(98, 102, 141));
        pnlEntradaNumero.setRoundBottomLeft(15);
        pnlEntradaNumero.setRoundBottomRight(15);
        pnlEntradaNumero.setRoundTopLeft(15);
        pnlEntradaNumero.setRoundTopRight(15);

        lblNumero.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        lblNumero.setForeground(new java.awt.Color(255, 255, 255));
        lblNumero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumero.setText("numero");
        lblNumero.setToolTipText("");

        txfNumero.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txfNumero.setForeground(new java.awt.Color(153, 153, 153));
        txfNumero.setText("  ingrese el numero de la computadora");
        txfNumero.setBorder(null);

        javax.swing.GroupLayout pnlEntradaNumeroLayout = new javax.swing.GroupLayout(pnlEntradaNumero);
        pnlEntradaNumero.setLayout(pnlEntradaNumeroLayout);
        pnlEntradaNumeroLayout.setHorizontalGroup(
            pnlEntradaNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 926, Short.MAX_VALUE)
            .addGroup(pnlEntradaNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlEntradaNumeroLayout.createSequentialGroup()
                    .addComponent(lblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 598, Short.MAX_VALUE)))
            .addGroup(pnlEntradaNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlEntradaNumeroLayout.createSequentialGroup()
                    .addGap(331, 331, 331)
                    .addComponent(txfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(35, Short.MAX_VALUE)))
        );
        pnlEntradaNumeroLayout.setVerticalGroup(
            pnlEntradaNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
            .addGroup(pnlEntradaNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlEntradaNumeroLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(lblNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addGap(11, 11, 11)))
            .addGroup(pnlEntradaNumeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlEntradaNumeroLayout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(txfNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addGap(9, 9, 9)))
        );

        pnlEntradaTipo.setBackground(new java.awt.Color(98, 102, 141));
        pnlEntradaTipo.setRoundBottomLeft(15);
        pnlEntradaTipo.setRoundBottomRight(15);
        pnlEntradaTipo.setRoundTopLeft(15);
        pnlEntradaTipo.setRoundTopRight(15);

        lblTipo.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(255, 255, 255));
        lblTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTipo.setText("tipo");
        lblTipo.setToolTipText("");

        pnlSeleccionTipo.setBackground(new java.awt.Color(32, 39, 116));
        pnlSeleccionTipo.setRoundBottomLeft(10);
        pnlSeleccionTipo.setRoundBottomRight(10);
        pnlSeleccionTipo.setRoundTopLeft(10);
        pnlSeleccionTipo.setRoundTopRight(10);

        lblSeleccionTipo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSeleccionTipo.setForeground(new java.awt.Color(255, 255, 255));
        lblSeleccionTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSeleccionTipo.setText("-- seleccione el tipo --");
        lblSeleccionTipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnlSeleccionTipoLayout = new javax.swing.GroupLayout(pnlSeleccionTipo);
        pnlSeleccionTipo.setLayout(pnlSeleccionTipoLayout);
        pnlSeleccionTipoLayout.setHorizontalGroup(
            pnlSeleccionTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSeleccionTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
        );
        pnlSeleccionTipoLayout.setVerticalGroup(
            pnlSeleccionTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSeleccionTipoLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lblSeleccionTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlEntradaTipoLayout = new javax.swing.GroupLayout(pnlEntradaTipo);
        pnlEntradaTipo.setLayout(pnlEntradaTipoLayout);
        pnlEntradaTipoLayout.setHorizontalGroup(
            pnlEntradaTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEntradaTipoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlSeleccionTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(pnlEntradaTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlEntradaTipoLayout.createSequentialGroup()
                    .addComponent(lblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 597, Short.MAX_VALUE)))
        );
        pnlEntradaTipoLayout.setVerticalGroup(
            pnlEntradaTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEntradaTipoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSeleccionTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlEntradaTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlEntradaTipoLayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(lblTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addGap(13, 13, 13)))
        );

        javax.swing.GroupLayout pnlContenidoOperacionLayout = new javax.swing.GroupLayout(pnlContenidoOperacion);
        pnlContenidoOperacion.setLayout(pnlContenidoOperacionLayout);
        pnlContenidoOperacionLayout.setHorizontalGroup(
            pnlContenidoOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenidoOperacionLayout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addGroup(pnlContenidoOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlEntradaNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlEntradaLaboratorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlEntradaIp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlEntradaTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlContenidoOperacionLayout.setVerticalGroup(
            pnlContenidoOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenidoOperacionLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(pnlEntradaLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlEntradaIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlEntradaNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlEntradaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        add(pnlContenidoOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 1310, 630));

        lblCancelar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCancelar.setForeground(new java.awt.Color(255, 255, 255));
        lblCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCancelar.setText("cancelar");
        lblCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCancelarMouseClicked(evt);
            }
        });
        add(lblCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 910, 330, 50));

        botonCancelar.setBackground(new java.awt.Color(212, 82, 82));
        add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 910, 330, 50));

        lblContinuar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblContinuar.setForeground(new java.awt.Color(255, 255, 255));
        lblContinuar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContinuar.setText("continuar");
        lblContinuar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(lblContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 910, 320, 50));

        botonContinuar.setBackground(new java.awt.Color(25, 50, 178));
        botonContinuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonContinuarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout botonContinuarLayout = new javax.swing.GroupLayout(botonContinuar);
        botonContinuar.setLayout(botonContinuarLayout);
        botonContinuarLayout.setHorizontalGroup(
            botonContinuarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        botonContinuarLayout.setVerticalGroup(
            botonContinuarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        add(botonContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 910, 320, 50));
    }// </editor-fold>//GEN-END:initComponents

    //opciones de navegacion
    private void lblCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelarMouseClicked
        presentacion_administrador.Controlador.mostrarVentanaInicio(frame);
    }//GEN-LAST:event_lblCancelarMouseClicked

    private void botonContinuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonContinuarMouseClicked
        mostrarVentanaComputadoraAgregaProgramas(frame);
    }//GEN-LAST:event_botonContinuarMouseClicked

    
    //opciones de control
    
    /**
     * ventana que permite continuar el proceso de agregar una computadora
     *
     * @param frame
     */
    public static void mostrarVentanaComputadoraAgregaProgramas(JFrame frame) {
        SwingUtilities.invokeLater(() -> {
            VentanaComputadoraAgregaProgramas ventana = new VentanaComputadoraAgregaProgramas(frame);
            frame.setContentPane(ventana);
            frame.revalidate();
        });
    }
    
    /**
     * ventana que permite continuar el proceso de agregar una computadora
     *
     * @param frame
     */
    public static void mostrarVentanaComputadoraAgregarConfirmacion(JFrame frame) {
        SwingUtilities.invokeLater(() -> {
            VentanaComputadoraAgregarConfirmar ventana = new VentanaComputadoraAgregarConfirmar(frame);
            frame.setContentPane(ventana);
            frame.revalidate();
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private presentacion_administrador.componentes.BotonCancelar botonCancelar;
    private presentacion_administrador.componentes.BotonSiguiente botonContinuar;
    private javax.swing.JLabel lblCancelar;
    private javax.swing.JLabel lblContinuar;
    private javax.swing.JLabel lblDos;
    private javax.swing.JLabel lblIp;
    private javax.swing.JLabel lblLaboratorio;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblSeleccionLaboratorio;
    private javax.swing.JLabel lblSeleccionTipo;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTituloOperacion;
    private javax.swing.JLabel lblTres;
    private javax.swing.JLabel lblUno;
    private presentacion_administrador.componentes.PanelRound pnlBarraProceso;
    private presentacion_administrador.componentes.PanelRound pnlContenidoOperacion;
    private presentacion_administrador.componentes.PanelRound pnlDos;
    private presentacion_administrador.componentes.PanelRound pnlEntradaIp;
    private presentacion_administrador.componentes.PanelRound pnlEntradaLaboratorio;
    private presentacion_administrador.componentes.PanelRound pnlEntradaNumero;
    private presentacion_administrador.componentes.PanelRound pnlEntradaTipo;
    private presentacion_administrador.componentes.PanelRound pnlSeleccionLaboratorio;
    private presentacion_administrador.componentes.PanelRound pnlSeleccionTipo;
    private presentacion_administrador.componentes.PanelRound pnlTituloOperacion;
    private presentacion_administrador.componentes.PanelRound pnlTres;
    private presentacion_administrador.componentes.PanelRound pnlUno;
    private javax.swing.JPanel separadorDosTres;
    private javax.swing.JPanel separadorUnoDos;
    private javax.swing.JTextField txfIp;
    private javax.swing.JTextField txfNumero;
    // End of variables declaration//GEN-END:variables
}
