package presentacion_administrador.vistas.computadoras.agregar_computadora;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author angel
 */
public class VentanaAgregarProgramas extends javax.swing.JPanel {

    private JFrame frame;

    /**
     * Creates new form VentanaBienvenida
     *
     * @param frame
     */
    public VentanaAgregarProgramas(JFrame frame) {
        initComponents();
        this.frame = frame;
        optBloqueos.setVisible(false);
        optComputadoras.setVisible(false);
        optLaboratorios.setVisible(false);
        optReportes.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNavegacion = new javax.swing.JPanel();
        btnComputadoras = new presentacion_administrador.componentes.BotonNavegador();
        lblComputadoras = new javax.swing.JLabel();
        btnBloqueos = new presentacion_administrador.componentes.BotonNavegador();
        lblAlumnos = new javax.swing.JLabel();
        btnLaboratorios = new presentacion_administrador.componentes.BotonNavegador();
        lblLaboratorios = new javax.swing.JLabel();
        btnReportes = new presentacion_administrador.componentes.BotonNavegador();
        lblReportes = new javax.swing.JLabel();
        optComputadoras = new javax.swing.JPanel();
        btnAgregarCompu = new presentacion_administrador.componentes.BotonNavegador();
        lblAgregarCompu = new javax.swing.JLabel();
        btnEliminarCompu = new presentacion_administrador.componentes.BotonNavegador();
        lblEliminarCompu = new javax.swing.JLabel();
        btnListarCompu = new presentacion_administrador.componentes.BotonNavegador();
        lblListarCompu = new javax.swing.JLabel();
        optBloqueos = new javax.swing.JPanel();
        btnBloquearAlumno = new presentacion_administrador.componentes.BotonNavegador();
        lblBloquearAlumno = new javax.swing.JLabel();
        btnDesbloquearAlumno = new presentacion_administrador.componentes.BotonNavegador();
        lblDesbloquearAlumno = new javax.swing.JLabel();
        btnListarBloqueos = new presentacion_administrador.componentes.BotonNavegador();
        listarBloqueos = new javax.swing.JLabel();
        optLaboratorios = new javax.swing.JPanel();
        btnAgregarLaboratorio = new presentacion_administrador.componentes.BotonNavegador();
        lblAgregarLaboratorio = new javax.swing.JLabel();
        btnModificarLaboratorio = new presentacion_administrador.componentes.BotonNavegador();
        lblModificarLaboratorio = new javax.swing.JLabel();
        btnListarLaboratorios = new presentacion_administrador.componentes.BotonNavegador();
        listarLaboratorios = new javax.swing.JLabel();
        optReportes = new javax.swing.JPanel();
        btnReporteCarreras = new presentacion_administrador.componentes.BotonNavegador();
        lblReporteCarreras = new javax.swing.JLabel();
        btnReporteBloqueos = new presentacion_administrador.componentes.BotonNavegador();
        lblReporteBloqueos = new javax.swing.JLabel();
        btnReporteCentros = new presentacion_administrador.componentes.BotonNavegador();
        lblReportesCentros = new javax.swing.JLabel();
        pnlBarraProceso = new presentacion_administrador.componentes.PanelRound();
        pnlUno = new presentacion_administrador.componentes.PanelRound();
        lblUno = new javax.swing.JLabel();
        pnlDos = new presentacion_administrador.componentes.PanelRound();
        lblDos = new javax.swing.JLabel();
        pnlTres = new presentacion_administrador.componentes.PanelRound();
        lblTres = new javax.swing.JLabel();
        separadorUnoDos = new javax.swing.JPanel();
        separadorDosTres = new javax.swing.JPanel();
        pnlTituloOperacion = new presentacion_administrador.componentes.PanelRound();
        lblTituloOperacion = new javax.swing.JLabel();
        pnlContenidoOperacion = new presentacion_administrador.componentes.PanelRound();
        lblCancelar = new javax.swing.JLabel();
        botonCancelar = new presentacion_administrador.componentes.BotonCancelar();
        lblContinuar = new javax.swing.JLabel();
        botonContinuar = new presentacion_administrador.componentes.BotonSiguiente();

        setBackground(new java.awt.Color(16, 20, 65));
        setMinimumSize(new java.awt.Dimension(1440, 1024));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1440, 1024));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlNavegacion.setOpaque(false);
        pnlNavegacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnComputadoras.setBackground(new java.awt.Color(32, 39, 116));
        btnComputadoras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnComputadorasMouseClicked(evt);
            }
        });

        lblComputadoras.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        lblComputadoras.setForeground(new java.awt.Color(255, 255, 255));
        lblComputadoras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComputadoras.setText("computadoras");
        lblComputadoras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnComputadorasLayout = new javax.swing.GroupLayout(btnComputadoras);
        btnComputadoras.setLayout(btnComputadorasLayout);
        btnComputadorasLayout.setHorizontalGroup(
            btnComputadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnComputadorasLayout.createSequentialGroup()
                .addComponent(lblComputadoras, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnComputadorasLayout.setVerticalGroup(
            btnComputadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblComputadoras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlNavegacion.add(btnComputadoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 50));

        btnBloqueos.setBackground(new java.awt.Color(32, 39, 116));
        btnBloqueos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBloqueosMouseClicked(evt);
            }
        });

        lblAlumnos.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        lblAlumnos.setForeground(new java.awt.Color(255, 255, 255));
        lblAlumnos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAlumnos.setText("bloqueos");
        lblAlumnos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnBloqueosLayout = new javax.swing.GroupLayout(btnBloqueos);
        btnBloqueos.setLayout(btnBloqueosLayout);
        btnBloqueosLayout.setHorizontalGroup(
            btnBloqueosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );
        btnBloqueosLayout.setVerticalGroup(
            btnBloqueosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAlumnos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlNavegacion.add(btnBloqueos, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 360, 50));

        btnLaboratorios.setBackground(new java.awt.Color(32, 39, 116));
        btnLaboratorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLaboratoriosMouseClicked(evt);
            }
        });

        lblLaboratorios.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        lblLaboratorios.setForeground(new java.awt.Color(255, 255, 255));
        lblLaboratorios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLaboratorios.setText("laboratorios");
        lblLaboratorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnLaboratoriosLayout = new javax.swing.GroupLayout(btnLaboratorios);
        btnLaboratorios.setLayout(btnLaboratoriosLayout);
        btnLaboratoriosLayout.setHorizontalGroup(
            btnLaboratoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLaboratorios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );
        btnLaboratoriosLayout.setVerticalGroup(
            btnLaboratoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLaboratorios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlNavegacion.add(btnLaboratorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 360, 50));

        btnReportes.setBackground(new java.awt.Color(32, 39, 116));
        btnReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReportesMouseClicked(evt);
            }
        });

        lblReportes.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        lblReportes.setForeground(new java.awt.Color(255, 255, 255));
        lblReportes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReportes.setText("reportes");
        lblReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnReportesLayout = new javax.swing.GroupLayout(btnReportes);
        btnReportes.setLayout(btnReportesLayout);
        btnReportesLayout.setHorizontalGroup(
            btnReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblReportes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );
        btnReportesLayout.setVerticalGroup(
            btnReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblReportes, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlNavegacion.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 0, 360, 50));

        add(pnlNavegacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 50));

        optComputadoras.setBackground(new java.awt.Color(32, 39, 116));
        optComputadoras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregarCompu.setBackground(new java.awt.Color(32, 39, 116));
        btnAgregarCompu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarCompuMouseClicked(evt);
            }
        });

        lblAgregarCompu.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        lblAgregarCompu.setForeground(new java.awt.Color(255, 255, 255));
        lblAgregarCompu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgregarCompu.setText("agregar computadora");
        lblAgregarCompu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnAgregarCompuLayout = new javax.swing.GroupLayout(btnAgregarCompu);
        btnAgregarCompu.setLayout(btnAgregarCompuLayout);
        btnAgregarCompuLayout.setHorizontalGroup(
            btnAgregarCompuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAgregarCompu, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        btnAgregarCompuLayout.setVerticalGroup(
            btnAgregarCompuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAgregarCompu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        optComputadoras.add(btnAgregarCompu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 50));

        btnEliminarCompu.setBackground(new java.awt.Color(32, 39, 116));
        btnEliminarCompu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarCompuMouseClicked(evt);
            }
        });

        lblEliminarCompu.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        lblEliminarCompu.setForeground(new java.awt.Color(255, 255, 255));
        lblEliminarCompu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEliminarCompu.setText("eliminar computadora");
        lblEliminarCompu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnEliminarCompuLayout = new javax.swing.GroupLayout(btnEliminarCompu);
        btnEliminarCompu.setLayout(btnEliminarCompuLayout);
        btnEliminarCompuLayout.setHorizontalGroup(
            btnEliminarCompuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEliminarCompu, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        btnEliminarCompuLayout.setVerticalGroup(
            btnEliminarCompuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEliminarCompu, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        optComputadoras.add(btnEliminarCompu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 340, 50));

        btnListarCompu.setBackground(new java.awt.Color(32, 39, 116));
        btnListarCompu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListarCompuMouseClicked(evt);
            }
        });

        lblListarCompu.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        lblListarCompu.setForeground(new java.awt.Color(255, 255, 255));
        lblListarCompu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblListarCompu.setText("listar computadora");
        lblListarCompu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnListarCompuLayout = new javax.swing.GroupLayout(btnListarCompu);
        btnListarCompu.setLayout(btnListarCompuLayout);
        btnListarCompuLayout.setHorizontalGroup(
            btnListarCompuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblListarCompu, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        btnListarCompuLayout.setVerticalGroup(
            btnListarCompuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblListarCompu, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        optComputadoras.add(btnListarCompu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 340, 40));

        add(optComputadoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 340, 160));

        optBloqueos.setBackground(new java.awt.Color(32, 39, 116));
        optBloqueos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBloquearAlumno.setBackground(new java.awt.Color(32, 39, 116));
        btnBloquearAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBloquearAlumnoMouseClicked(evt);
            }
        });

        lblBloquearAlumno.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        lblBloquearAlumno.setForeground(new java.awt.Color(255, 255, 255));
        lblBloquearAlumno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBloquearAlumno.setText("bloquear alumno");
        lblBloquearAlumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnBloquearAlumnoLayout = new javax.swing.GroupLayout(btnBloquearAlumno);
        btnBloquearAlumno.setLayout(btnBloquearAlumnoLayout);
        btnBloquearAlumnoLayout.setHorizontalGroup(
            btnBloquearAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBloquearAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        btnBloquearAlumnoLayout.setVerticalGroup(
            btnBloquearAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBloquearAlumno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        optBloqueos.add(btnBloquearAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 50));

        btnDesbloquearAlumno.setBackground(new java.awt.Color(32, 39, 116));
        btnDesbloquearAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDesbloquearAlumnoMouseClicked(evt);
            }
        });

        lblDesbloquearAlumno.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        lblDesbloquearAlumno.setForeground(new java.awt.Color(255, 255, 255));
        lblDesbloquearAlumno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDesbloquearAlumno.setText("desbloquear alumno");
        lblDesbloquearAlumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnDesbloquearAlumnoLayout = new javax.swing.GroupLayout(btnDesbloquearAlumno);
        btnDesbloquearAlumno.setLayout(btnDesbloquearAlumnoLayout);
        btnDesbloquearAlumnoLayout.setHorizontalGroup(
            btnDesbloquearAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDesbloquearAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        btnDesbloquearAlumnoLayout.setVerticalGroup(
            btnDesbloquearAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDesbloquearAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        optBloqueos.add(btnDesbloquearAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 340, 50));

        btnListarBloqueos.setBackground(new java.awt.Color(32, 39, 116));
        btnListarBloqueos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListarBloqueosMouseClicked(evt);
            }
        });

        listarBloqueos.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        listarBloqueos.setForeground(new java.awt.Color(255, 255, 255));
        listarBloqueos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listarBloqueos.setText("listar bloqueos");
        listarBloqueos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnListarBloqueosLayout = new javax.swing.GroupLayout(btnListarBloqueos);
        btnListarBloqueos.setLayout(btnListarBloqueosLayout);
        btnListarBloqueosLayout.setHorizontalGroup(
            btnListarBloqueosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listarBloqueos, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        btnListarBloqueosLayout.setVerticalGroup(
            btnListarBloqueosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listarBloqueos, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        optBloqueos.add(btnListarBloqueos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 340, 40));

        add(optBloqueos, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 340, 160));

        optLaboratorios.setBackground(new java.awt.Color(32, 39, 116));
        optLaboratorios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregarLaboratorio.setBackground(new java.awt.Color(32, 39, 116));
        btnAgregarLaboratorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarLaboratorioMouseClicked(evt);
            }
        });

        lblAgregarLaboratorio.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        lblAgregarLaboratorio.setForeground(new java.awt.Color(255, 255, 255));
        lblAgregarLaboratorio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgregarLaboratorio.setText("agregar laboratorio");
        lblAgregarLaboratorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnAgregarLaboratorioLayout = new javax.swing.GroupLayout(btnAgregarLaboratorio);
        btnAgregarLaboratorio.setLayout(btnAgregarLaboratorioLayout);
        btnAgregarLaboratorioLayout.setHorizontalGroup(
            btnAgregarLaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAgregarLaboratorio, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        btnAgregarLaboratorioLayout.setVerticalGroup(
            btnAgregarLaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAgregarLaboratorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        optLaboratorios.add(btnAgregarLaboratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 50));

        btnModificarLaboratorio.setBackground(new java.awt.Color(32, 39, 116));
        btnModificarLaboratorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarLaboratorioMouseClicked(evt);
            }
        });

        lblModificarLaboratorio.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        lblModificarLaboratorio.setForeground(new java.awt.Color(255, 255, 255));
        lblModificarLaboratorio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModificarLaboratorio.setText("modificar laboratorio");
        lblModificarLaboratorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnModificarLaboratorioLayout = new javax.swing.GroupLayout(btnModificarLaboratorio);
        btnModificarLaboratorio.setLayout(btnModificarLaboratorioLayout);
        btnModificarLaboratorioLayout.setHorizontalGroup(
            btnModificarLaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblModificarLaboratorio, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        btnModificarLaboratorioLayout.setVerticalGroup(
            btnModificarLaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblModificarLaboratorio, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        optLaboratorios.add(btnModificarLaboratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 340, 50));

        btnListarLaboratorios.setBackground(new java.awt.Color(32, 39, 116));
        btnListarLaboratorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListarLaboratoriosMouseClicked(evt);
            }
        });

        listarLaboratorios.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        listarLaboratorios.setForeground(new java.awt.Color(255, 255, 255));
        listarLaboratorios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listarLaboratorios.setText("listar laboratorios");
        listarLaboratorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnListarLaboratoriosLayout = new javax.swing.GroupLayout(btnListarLaboratorios);
        btnListarLaboratorios.setLayout(btnListarLaboratoriosLayout);
        btnListarLaboratoriosLayout.setHorizontalGroup(
            btnListarLaboratoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listarLaboratorios, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        btnListarLaboratoriosLayout.setVerticalGroup(
            btnListarLaboratoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listarLaboratorios, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        optLaboratorios.add(btnListarLaboratorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 340, 40));

        add(optLaboratorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 50, 340, 160));

        optReportes.setBackground(new java.awt.Color(32, 39, 116));
        optReportes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnReporteCarreras.setBackground(new java.awt.Color(32, 39, 116));
        btnReporteCarreras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReporteCarrerasMouseClicked(evt);
            }
        });

        lblReporteCarreras.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        lblReporteCarreras.setForeground(new java.awt.Color(255, 255, 255));
        lblReporteCarreras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReporteCarreras.setText("reporte carreras");
        lblReporteCarreras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnReporteCarrerasLayout = new javax.swing.GroupLayout(btnReporteCarreras);
        btnReporteCarreras.setLayout(btnReporteCarrerasLayout);
        btnReporteCarrerasLayout.setHorizontalGroup(
            btnReporteCarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblReporteCarreras, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        btnReporteCarrerasLayout.setVerticalGroup(
            btnReporteCarrerasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblReporteCarreras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        optReportes.add(btnReporteCarreras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 50));

        btnReporteBloqueos.setBackground(new java.awt.Color(32, 39, 116));
        btnReporteBloqueos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReporteBloqueosMouseClicked(evt);
            }
        });

        lblReporteBloqueos.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        lblReporteBloqueos.setForeground(new java.awt.Color(255, 255, 255));
        lblReporteBloqueos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReporteBloqueos.setText("reporte bloqueos");
        lblReporteBloqueos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnReporteBloqueosLayout = new javax.swing.GroupLayout(btnReporteBloqueos);
        btnReporteBloqueos.setLayout(btnReporteBloqueosLayout);
        btnReporteBloqueosLayout.setHorizontalGroup(
            btnReporteBloqueosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblReporteBloqueos, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        btnReporteBloqueosLayout.setVerticalGroup(
            btnReporteBloqueosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblReporteBloqueos, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        optReportes.add(btnReporteBloqueos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 340, 50));

        btnReporteCentros.setBackground(new java.awt.Color(32, 39, 116));
        btnReporteCentros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReporteCentrosMouseClicked(evt);
            }
        });

        lblReportesCentros.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        lblReportesCentros.setForeground(new java.awt.Color(255, 255, 255));
        lblReportesCentros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReportesCentros.setText("reporte centros");
        lblReportesCentros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnReporteCentrosLayout = new javax.swing.GroupLayout(btnReporteCentros);
        btnReporteCentros.setLayout(btnReporteCentrosLayout);
        btnReporteCentrosLayout.setHorizontalGroup(
            btnReporteCentrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblReportesCentros, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        btnReporteCentrosLayout.setVerticalGroup(
            btnReporteCentrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblReportesCentros, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        optReportes.add(btnReporteCentros, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 340, 40));

        add(optReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 50, 340, 160));

        pnlBarraProceso.setBackground(new java.awt.Color(32, 39, 116));
        pnlBarraProceso.setRoundTopLeft(15);
        pnlBarraProceso.setRoundTopRight(15);
        pnlBarraProceso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlUno.setBackground(new java.awt.Color(25, 50, 178));
        pnlUno.setRoundBottomLeft(200);
        pnlUno.setRoundBottomRight(200);
        pnlUno.setRoundTopLeft(200);
        pnlUno.setRoundTopRight(200);

        lblUno.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblUno.setForeground(new java.awt.Color(255, 255, 255));
        lblUno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUno.setText("1");

        javax.swing.GroupLayout pnlUnoLayout = new javax.swing.GroupLayout(pnlUno);
        pnlUno.setLayout(pnlUnoLayout);
        pnlUnoLayout.setHorizontalGroup(
            pnlUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUno, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        pnlUnoLayout.setVerticalGroup(
            pnlUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUno, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlBarraProceso.add(pnlUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, 50));

        pnlDos.setBackground(new java.awt.Color(25, 50, 178));
        pnlDos.setRoundBottomLeft(200);
        pnlDos.setRoundBottomRight(200);
        pnlDos.setRoundTopLeft(200);
        pnlDos.setRoundTopRight(200);

        lblDos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDos.setForeground(new java.awt.Color(255, 255, 255));
        lblDos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDos.setText("2");

        javax.swing.GroupLayout pnlDosLayout = new javax.swing.GroupLayout(pnlDos);
        pnlDos.setLayout(pnlDosLayout);
        pnlDosLayout.setHorizontalGroup(
            pnlDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDos, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        pnlDosLayout.setVerticalGroup(
            pnlDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDos, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlBarraProceso.add(pnlDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 50, 50));

        pnlTres.setBackground(new java.awt.Color(105, 111, 153));
        pnlTres.setRoundBottomLeft(200);
        pnlTres.setRoundBottomRight(200);
        pnlTres.setRoundTopLeft(200);
        pnlTres.setRoundTopRight(200);

        lblTres.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTres.setForeground(new java.awt.Color(255, 255, 255));
        lblTres.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTres.setText("3");

        javax.swing.GroupLayout pnlTresLayout = new javax.swing.GroupLayout(pnlTres);
        pnlTres.setLayout(pnlTresLayout);
        pnlTresLayout.setHorizontalGroup(
            pnlTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTres, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        pnlTresLayout.setVerticalGroup(
            pnlTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTres, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlBarraProceso.add(pnlTres, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 50, 50));

        separadorUnoDos.setBackground(new java.awt.Color(16, 20, 65));

        javax.swing.GroupLayout separadorUnoDosLayout = new javax.swing.GroupLayout(separadorUnoDos);
        separadorUnoDos.setLayout(separadorUnoDosLayout);
        separadorUnoDosLayout.setHorizontalGroup(
            separadorUnoDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        separadorUnoDosLayout.setVerticalGroup(
            separadorUnoDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlBarraProceso.add(separadorUnoDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 90, -1));

        separadorDosTres.setBackground(new java.awt.Color(105, 111, 153));

        javax.swing.GroupLayout separadorDosTresLayout = new javax.swing.GroupLayout(separadorDosTres);
        separadorDosTres.setLayout(separadorDosTresLayout);
        separadorDosTresLayout.setHorizontalGroup(
            separadorDosTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        separadorDosTresLayout.setVerticalGroup(
            separadorDosTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlBarraProceso.add(separadorDosTres, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 90, -1));

        add(pnlBarraProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 70, 330, 70));

        pnlTituloOperacion.setBackground(new java.awt.Color(105, 111, 153));
        pnlTituloOperacion.setRoundTopLeft(20);
        pnlTituloOperacion.setRoundTopRight(20);

        lblTituloOperacion.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        lblTituloOperacion.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloOperacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloOperacion.setText("seleccion de programas");
        lblTituloOperacion.setToolTipText("");
        lblTituloOperacion.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout pnlTituloOperacionLayout = new javax.swing.GroupLayout(pnlTituloOperacion);
        pnlTituloOperacion.setLayout(pnlTituloOperacionLayout);
        pnlTituloOperacionLayout.setHorizontalGroup(
            pnlTituloOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTituloOperacion, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );
        pnlTituloOperacionLayout.setVerticalGroup(
            pnlTituloOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTituloOperacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        add(pnlTituloOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 620, 50));

        pnlContenidoOperacion.setBackground(new java.awt.Color(25, 30, 69));
        pnlContenidoOperacion.setRoundBottomLeft(20);
        pnlContenidoOperacion.setRoundBottomRight(20);

        javax.swing.GroupLayout pnlContenidoOperacionLayout = new javax.swing.GroupLayout(pnlContenidoOperacion);
        pnlContenidoOperacion.setLayout(pnlContenidoOperacionLayout);
        pnlContenidoOperacionLayout.setHorizontalGroup(
            pnlContenidoOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1310, Short.MAX_VALUE)
        );
        pnlContenidoOperacionLayout.setVerticalGroup(
            pnlContenidoOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        add(pnlContenidoOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 1310, 670));

        lblCancelar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCancelar.setForeground(new java.awt.Color(255, 255, 255));
        lblCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCancelar.setText("cancelar");
        lblCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCancelarMouseClicked(evt);
            }
        });
        add(lblCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 910, 330, 50));

        botonCancelar.setBackground(new java.awt.Color(212, 82, 82));
        add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 910, 330, 50));

        lblContinuar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblContinuar.setForeground(new java.awt.Color(255, 255, 255));
        lblContinuar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContinuar.setText("continuar");
        lblContinuar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(lblContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 910, 320, 50));

        botonContinuar.setBackground(new java.awt.Color(25, 50, 178));
        botonContinuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonContinuarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout botonContinuarLayout = new javax.swing.GroupLayout(botonContinuar);
        botonContinuar.setLayout(botonContinuarLayout);
        botonContinuarLayout.setHorizontalGroup(
            botonContinuarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        botonContinuarLayout.setVerticalGroup(
            botonContinuarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        add(botonContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 910, 320, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btnComputadorasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComputadorasMouseClicked
        // TODO add your handling code here:
        SwingUtilities.invokeLater(() -> {
            optComputadoras.setVisible(!optComputadoras.isVisible());
        });
    }//GEN-LAST:event_btnComputadorasMouseClicked

    private void btnBloqueosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBloqueosMouseClicked
        // TODO add your handling code here:
        SwingUtilities.invokeLater(() -> {
            optBloqueos.setVisible(!optBloqueos.isVisible());
        });
    }//GEN-LAST:event_btnBloqueosMouseClicked

    private void btnLaboratoriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaboratoriosMouseClicked
        // TODO add your handling code here:
        SwingUtilities.invokeLater(() -> {
            optLaboratorios.setVisible(!optLaboratorios.isVisible());
        });
    }//GEN-LAST:event_btnLaboratoriosMouseClicked

    private void btnReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesMouseClicked
        // TODO add your handling code here:
        SwingUtilities.invokeLater(() -> {
            optReportes.setVisible(!optReportes.isVisible());
        });
    }//GEN-LAST:event_btnReportesMouseClicked

    
    //opociones computadoras
    private void btnEliminarCompuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarCompuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarCompuMouseClicked

    private void btnListarCompuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarCompuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListarCompuMouseClicked

    
    //opociones bloqueos
    private void btnBloquearAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBloquearAlumnoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBloquearAlumnoMouseClicked

    private void btnDesbloquearAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDesbloquearAlumnoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDesbloquearAlumnoMouseClicked

    private void btnListarBloqueosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarBloqueosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListarBloqueosMouseClicked

    
    //opciones de laboratorios
    private void btnAgregarLaboratorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarLaboratorioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarLaboratorioMouseClicked

    private void btnModificarLaboratorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarLaboratorioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarLaboratorioMouseClicked

    private void btnListarLaboratoriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarLaboratoriosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListarLaboratoriosMouseClicked

    
    //opciones de reportes
    private void btnReporteCarrerasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteCarrerasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReporteCarrerasMouseClicked

    private void btnReporteBloqueosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteBloqueosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReporteBloqueosMouseClicked

    private void btnReporteCentrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteCentrosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReporteCentrosMouseClicked

    //opciones de navegacion
    private void lblCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelarMouseClicked
        // TODO add your handling code here:
        presentacion_administrador.Controlador.mostrarVentanaAgregarComputadora(frame);
    }//GEN-LAST:event_lblCancelarMouseClicked

    private void btnAgregarCompuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarCompuMouseClicked
        // TODO add your handling code here:
        presentacion_administrador.Controlador.mostrarVentanaAgregarComputadora(frame);
    }//GEN-LAST:event_btnAgregarCompuMouseClicked

    private void botonContinuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonContinuarMouseClicked
        // TODO add your handling code here:
        presentacion_administrador.Controlador.mostrarVentanaAgregarConfirmacion(frame);
    }//GEN-LAST:event_botonContinuarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private presentacion_administrador.componentes.BotonCancelar botonCancelar;
    private presentacion_administrador.componentes.BotonSiguiente botonContinuar;
    private javax.swing.JPanel btnAgregarCompu;
    private javax.swing.JPanel btnAgregarLaboratorio;
    private javax.swing.JPanel btnBloquearAlumno;
    private javax.swing.JPanel btnBloqueos;
    private javax.swing.JPanel btnComputadoras;
    private javax.swing.JPanel btnDesbloquearAlumno;
    private javax.swing.JPanel btnEliminarCompu;
    private javax.swing.JPanel btnLaboratorios;
    private javax.swing.JPanel btnListarBloqueos;
    private javax.swing.JPanel btnListarCompu;
    private javax.swing.JPanel btnListarLaboratorios;
    private javax.swing.JPanel btnModificarLaboratorio;
    private javax.swing.JPanel btnReporteBloqueos;
    private javax.swing.JPanel btnReporteCarreras;
    private javax.swing.JPanel btnReporteCentros;
    private javax.swing.JPanel btnReportes;
    private javax.swing.JLabel lblAgregarCompu;
    private javax.swing.JLabel lblAgregarLaboratorio;
    private javax.swing.JLabel lblAlumnos;
    private javax.swing.JLabel lblBloquearAlumno;
    private javax.swing.JLabel lblCancelar;
    private javax.swing.JLabel lblComputadoras;
    private javax.swing.JLabel lblContinuar;
    private javax.swing.JLabel lblDesbloquearAlumno;
    private javax.swing.JLabel lblDos;
    private javax.swing.JLabel lblEliminarCompu;
    private javax.swing.JLabel lblLaboratorios;
    private javax.swing.JLabel lblListarCompu;
    private javax.swing.JLabel lblModificarLaboratorio;
    private javax.swing.JLabel lblReporteBloqueos;
    private javax.swing.JLabel lblReporteCarreras;
    private javax.swing.JLabel lblReportes;
    private javax.swing.JLabel lblReportesCentros;
    private javax.swing.JLabel lblTituloOperacion;
    private javax.swing.JLabel lblTres;
    private javax.swing.JLabel lblUno;
    private javax.swing.JLabel listarBloqueos;
    private javax.swing.JLabel listarLaboratorios;
    private javax.swing.JPanel optBloqueos;
    private javax.swing.JPanel optComputadoras;
    private javax.swing.JPanel optLaboratorios;
    private javax.swing.JPanel optReportes;
    private presentacion_administrador.componentes.PanelRound pnlBarraProceso;
    private presentacion_administrador.componentes.PanelRound pnlContenidoOperacion;
    private presentacion_administrador.componentes.PanelRound pnlDos;
    private javax.swing.JPanel pnlNavegacion;
    private presentacion_administrador.componentes.PanelRound pnlTituloOperacion;
    private presentacion_administrador.componentes.PanelRound pnlTres;
    private presentacion_administrador.componentes.PanelRound pnlUno;
    private javax.swing.JPanel separadorDosTres;
    private javax.swing.JPanel separadorUnoDos;
    // End of variables declaration//GEN-END:variables
}
