package presentacion_administrador.vistas.laboratorios.agregar_laboratorio;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import presentacion_administrador.componentes.PanelNavegacion;

/**
 *
 * @author erwbyel
 */
public class VentanaLaboratorioAgrega extends javax.swing.JPanel {

    private JFrame frame;

    /**
     * Creates new form VentanaBienvenida
     *
     * @param frame
     */
    public VentanaLaboratorioAgrega(JFrame frame) {
        this.frame = frame;
        initComponents();
        PanelNavegacion pnlNavegacion = new PanelNavegacion(frame);
        add(pnlNavegacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 200));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBarraProceso = new presentacion_administrador.componentes.PanelRound();
        pnlUno = new presentacion_administrador.componentes.PanelRound();
        lblUno = new javax.swing.JLabel();
        pnlDos = new presentacion_administrador.componentes.PanelRound();
        lblDos = new javax.swing.JLabel();
        separadorUnoDos = new javax.swing.JPanel();
        pnlTituloOperacion = new presentacion_administrador.componentes.PanelRound();
        lblTituloOperacion = new javax.swing.JLabel();
        pnlContenidoOperacion = new presentacion_administrador.componentes.PanelRound();
        pnlEntradaIp = new presentacion_administrador.componentes.PanelRound();
        lblIp = new javax.swing.JLabel();
        txfIp = new javax.swing.JTextField();
        pnlEntradaTipo = new presentacion_administrador.componentes.PanelRound();
        lblTipo = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        lblCancelar = new javax.swing.JLabel();
        botonCancelar = new presentacion_administrador.componentes.BotonCancelar();
        lblContinuar = new javax.swing.JLabel();
        botonContinuar = new presentacion_administrador.componentes.BotonSiguiente();

        setBackground(new java.awt.Color(16, 20, 65));
        setMinimumSize(new java.awt.Dimension(1440, 1024));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1440, 1024));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBarraProceso.setBackground(new java.awt.Color(32, 39, 116));
        pnlBarraProceso.setRoundTopLeft(15);
        pnlBarraProceso.setRoundTopRight(15);
        pnlBarraProceso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlUno.setBackground(new java.awt.Color(25, 50, 178));
        pnlUno.setRoundBottomLeft(200);
        pnlUno.setRoundBottomRight(200);
        pnlUno.setRoundTopLeft(200);
        pnlUno.setRoundTopRight(200);

        lblUno.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblUno.setForeground(new java.awt.Color(255, 255, 255));
        lblUno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUno.setText("1");

        javax.swing.GroupLayout pnlUnoLayout = new javax.swing.GroupLayout(pnlUno);
        pnlUno.setLayout(pnlUnoLayout);
        pnlUnoLayout.setHorizontalGroup(
            pnlUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUno, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        pnlUnoLayout.setVerticalGroup(
            pnlUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUno, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlBarraProceso.add(pnlUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, 50));

        pnlDos.setBackground(new java.awt.Color(105, 111, 153));
        pnlDos.setRoundBottomLeft(200);
        pnlDos.setRoundBottomRight(200);
        pnlDos.setRoundTopLeft(200);
        pnlDos.setRoundTopRight(200);

        lblDos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDos.setForeground(new java.awt.Color(255, 255, 255));
        lblDos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDos.setText("2");

        javax.swing.GroupLayout pnlDosLayout = new javax.swing.GroupLayout(pnlDos);
        pnlDos.setLayout(pnlDosLayout);
        pnlDosLayout.setHorizontalGroup(
            pnlDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDos, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        pnlDosLayout.setVerticalGroup(
            pnlDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDos, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnlBarraProceso.add(pnlDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 50, 50));

        separadorUnoDos.setBackground(new java.awt.Color(105, 111, 153));

        javax.swing.GroupLayout separadorUnoDosLayout = new javax.swing.GroupLayout(separadorUnoDos);
        separadorUnoDos.setLayout(separadorUnoDosLayout);
        separadorUnoDosLayout.setHorizontalGroup(
            separadorUnoDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        separadorUnoDosLayout.setVerticalGroup(
            separadorUnoDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlBarraProceso.add(separadorUnoDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 90, -1));

        add(pnlBarraProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 190, 210, 70));

        pnlTituloOperacion.setBackground(new java.awt.Color(105, 111, 153));
        pnlTituloOperacion.setRoundTopLeft(20);
        pnlTituloOperacion.setRoundTopRight(20);

        lblTituloOperacion.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        lblTituloOperacion.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloOperacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloOperacion.setText("agregar laboratorio");
        lblTituloOperacion.setToolTipText("");
        lblTituloOperacion.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout pnlTituloOperacionLayout = new javax.swing.GroupLayout(pnlTituloOperacion);
        pnlTituloOperacion.setLayout(pnlTituloOperacionLayout);
        pnlTituloOperacionLayout.setHorizontalGroup(
            pnlTituloOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTituloOperacion, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );
        pnlTituloOperacionLayout.setVerticalGroup(
            pnlTituloOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTituloOperacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        add(pnlTituloOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 620, 50));

        pnlContenidoOperacion.setBackground(new java.awt.Color(25, 30, 69));
        pnlContenidoOperacion.setRoundBottomLeft(20);
        pnlContenidoOperacion.setRoundBottomRight(20);

        pnlEntradaIp.setBackground(new java.awt.Color(98, 102, 141));
        pnlEntradaIp.setRoundBottomLeft(15);
        pnlEntradaIp.setRoundBottomRight(15);
        pnlEntradaIp.setRoundTopLeft(15);
        pnlEntradaIp.setRoundTopRight(15);

        lblIp.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        lblIp.setForeground(new java.awt.Color(255, 255, 255));
        lblIp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIp.setText("nombre laboratorio");
        lblIp.setToolTipText("");

        txfIp.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txfIp.setForeground(new java.awt.Color(153, 153, 153));
        txfIp.setText("  ingrese el nombre del laboratorio");
        txfIp.setBorder(null);

        javax.swing.GroupLayout pnlEntradaIpLayout = new javax.swing.GroupLayout(pnlEntradaIp);
        pnlEntradaIp.setLayout(pnlEntradaIpLayout);
        pnlEntradaIpLayout.setHorizontalGroup(
            pnlEntradaIpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEntradaIpLayout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(txfIp, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(pnlEntradaIpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlEntradaIpLayout.createSequentialGroup()
                    .addComponent(lblIp, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 597, Short.MAX_VALUE)))
        );
        pnlEntradaIpLayout.setVerticalGroup(
            pnlEntradaIpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEntradaIpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txfIp, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlEntradaIpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlEntradaIpLayout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(lblIp, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addGap(8, 8, 8)))
        );

        pnlEntradaTipo.setBackground(new java.awt.Color(98, 102, 141));
        pnlEntradaTipo.setRoundBottomLeft(15);
        pnlEntradaTipo.setRoundBottomRight(15);
        pnlEntradaTipo.setRoundTopLeft(15);
        pnlEntradaTipo.setRoundTopRight(15);

        lblTipo.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(255, 255, 255));
        lblTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTipo.setText("unidad");
        lblTipo.setToolTipText("");

        jTextField1.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setText("id de la unidad academica");

        javax.swing.GroupLayout pnlEntradaTipoLayout = new javax.swing.GroupLayout(pnlEntradaTipo);
        pnlEntradaTipo.setLayout(pnlEntradaTipoLayout);
        pnlEntradaTipoLayout.setHorizontalGroup(
            pnlEntradaTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEntradaTipoLayout.createSequentialGroup()
                .addComponent(lblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlEntradaTipoLayout.setVerticalGroup(
            pnlEntradaTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEntradaTipoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addGap(13, 13, 13))
            .addGroup(pnlEntradaTipoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlContenidoOperacionLayout = new javax.swing.GroupLayout(pnlContenidoOperacion);
        pnlContenidoOperacion.setLayout(pnlContenidoOperacionLayout);
        pnlContenidoOperacionLayout.setHorizontalGroup(
            pnlContenidoOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenidoOperacionLayout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addGroup(pnlContenidoOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlEntradaIp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlEntradaTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        pnlContenidoOperacionLayout.setVerticalGroup(
            pnlContenidoOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenidoOperacionLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(pnlEntradaIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlEntradaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(401, Short.MAX_VALUE))
        );

        add(pnlContenidoOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 1310, 630));

        lblCancelar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCancelar.setForeground(new java.awt.Color(255, 255, 255));
        lblCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCancelar.setText("cancelar");
        lblCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCancelarMouseClicked(evt);
            }
        });
        add(lblCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 910, 330, 50));

        botonCancelar.setBackground(new java.awt.Color(212, 82, 82));
        add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 910, 330, 50));

        lblContinuar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblContinuar.setForeground(new java.awt.Color(255, 255, 255));
        lblContinuar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContinuar.setText("continuar");
        lblContinuar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(lblContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 910, 320, 50));

        botonContinuar.setBackground(new java.awt.Color(25, 50, 178));
        botonContinuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonContinuarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout botonContinuarLayout = new javax.swing.GroupLayout(botonContinuar);
        botonContinuar.setLayout(botonContinuarLayout);
        botonContinuarLayout.setHorizontalGroup(
            botonContinuarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        botonContinuarLayout.setVerticalGroup(
            botonContinuarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        add(botonContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 910, 320, 50));
    }// </editor-fold>//GEN-END:initComponents

    //opciones de navegacion
    private void lblCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelarMouseClicked
        presentacion_administrador.Controlador.mostrarVentanaInicio(frame);
    }//GEN-LAST:event_lblCancelarMouseClicked

    private void botonContinuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonContinuarMouseClicked
        mostrarVentanaLaboratorioAgregaConfirmacion(frame);
    }//GEN-LAST:event_botonContinuarMouseClicked

    /**
     * ventana que permite continuar el proceso de agregar un laboratorio
     *
     * @param frame
     */
    public static void mostrarVentanaLaboratorioAgregaConfirmacion(JFrame frame) {
        SwingUtilities.invokeLater(() -> {
            VentanaLaboratorioAgregaConfirmar ventana = new VentanaLaboratorioAgregaConfirmar(frame);
            frame.setContentPane(ventana);
            frame.revalidate();
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private presentacion_administrador.componentes.BotonCancelar botonCancelar;
    private presentacion_administrador.componentes.BotonSiguiente botonContinuar;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblCancelar;
    private javax.swing.JLabel lblContinuar;
    private javax.swing.JLabel lblDos;
    private javax.swing.JLabel lblIp;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTituloOperacion;
    private javax.swing.JLabel lblUno;
    private presentacion_administrador.componentes.PanelRound pnlBarraProceso;
    private presentacion_administrador.componentes.PanelRound pnlContenidoOperacion;
    private presentacion_administrador.componentes.PanelRound pnlDos;
    private presentacion_administrador.componentes.PanelRound pnlEntradaIp;
    private presentacion_administrador.componentes.PanelRound pnlEntradaTipo;
    private presentacion_administrador.componentes.PanelRound pnlTituloOperacion;
    private presentacion_administrador.componentes.PanelRound pnlUno;
    private javax.swing.JPanel separadorUnoDos;
    private javax.swing.JTextField txfIp;
    // End of variables declaration//GEN-END:variables
}
