
package presentacion_administrador.componentes.registros;

/**
 *
 * @author erwbyel
 */
public class RegistroProgramas extends javax.swing.JPanel {

    private boolean estado = false;
    
    /**
     * Creates new form RegistroProgramas
     * @param numero
     * @param nombre
     * @param version
     */
    public RegistroProgramas(String numero,String nombre, String version) {
        initComponents();
        lblNumero.setText(numero);
        lblNombre.setText(nombre);
        lblVersion.setText(version);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRegistro = new javax.swing.JPanel();
        lblNumero = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblVersion = new javax.swing.JLabel();
        btnUsarSoftware = new presentacion_administrador.componentes.PanelRound();
        lblUsar = new javax.swing.JLabel();

        pnlRegistro.setBackground(new java.awt.Color(61, 66, 105));
        pnlRegistro.setPreferredSize(new java.awt.Dimension(1021, 40));
        pnlRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNumero.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        lblNumero.setForeground(new java.awt.Color(255, 255, 255));
        lblNumero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumero.setText("1");
        pnlRegistro.add(lblNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        lblNombre.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre.setText("nombre");
        pnlRegistro.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 350, 40));

        lblVersion.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        lblVersion.setForeground(new java.awt.Color(255, 255, 255));
        lblVersion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVersion.setText("version");
        pnlRegistro.add(lblVersion, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 320, 41));

        btnUsarSoftware.setBackground(new java.awt.Color(25, 50, 178));
        btnUsarSoftware.setRoundBottomLeft(15);
        btnUsarSoftware.setRoundBottomRight(15);
        btnUsarSoftware.setRoundTopLeft(15);
        btnUsarSoftware.setRoundTopRight(15);
        btnUsarSoftware.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUsarSoftwareMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUsarSoftwareMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUsarSoftwareMouseExited(evt);
            }
        });

        lblUsar.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        lblUsar.setForeground(new java.awt.Color(255, 255, 255));
        lblUsar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsar.setText("USAR");
        lblUsar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnUsarSoftwareLayout = new javax.swing.GroupLayout(btnUsarSoftware);
        btnUsarSoftware.setLayout(btnUsarSoftwareLayout);
        btnUsarSoftwareLayout.setHorizontalGroup(
            btnUsarSoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUsar, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        btnUsarSoftwareLayout.setVerticalGroup(
            btnUsarSoftwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUsar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        pnlRegistro.add(btnUsarSoftware, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 5, 170, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsarSoftwareMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsarSoftwareMouseEntered
        btnUsarSoftware.setBackground(new java.awt.Color(255, 255, 255));
        lblUsar.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_btnUsarSoftwareMouseEntered

    private void btnUsarSoftwareMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsarSoftwareMouseExited
        btnUsarSoftware.setBackground(new java.awt.Color(25, 50, 178));
        lblUsar.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_btnUsarSoftwareMouseExited

    private void btnUsarSoftwareMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsarSoftwareMouseClicked
        estado = !estado;
        if(estado){
            lblUsar.setText("QUITAR");
        } else {
            lblUsar.setText("USAR");
        }
    }//GEN-LAST:event_btnUsarSoftwareMouseClicked

    public boolean getEstado(){
        return this.estado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private presentacion_administrador.componentes.PanelRound btnUsarSoftware;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblUsar;
    private javax.swing.JLabel lblVersion;
    private javax.swing.JPanel pnlRegistro;
    // End of variables declaration//GEN-END:variables
}
