
package presentacion_administrador.componentes.registros;

/**
 *
 * @author erwbyel
 */
public class RegistroBloqueos extends javax.swing.JPanel {
 
    /**
     * Creates new form RegistroProgramas
     * @param numero
     * @param nombre
     * @param version
     */
    public RegistroBloqueos(String numero,String nombre, String version) {
        initComponents();
        lblNumero.setText(numero);
        lblNombre.setText(nombre);
        lblVersion.setText(version);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRegistro = new javax.swing.JPanel();
        lblNumero = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblVersion = new javax.swing.JLabel();

        pnlRegistro.setBackground(new java.awt.Color(61, 66, 105));
        pnlRegistro.setPreferredSize(new java.awt.Dimension(1021, 40));
        pnlRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNumero.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        lblNumero.setForeground(new java.awt.Color(255, 255, 255));
        lblNumero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumero.setText("1");
        pnlRegistro.add(lblNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        lblNombre.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre.setText("nombre");
        pnlRegistro.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 350, 40));

        lblVersion.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        lblVersion.setForeground(new java.awt.Color(255, 255, 255));
        lblVersion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVersion.setText("version");
        pnlRegistro.add(lblVersion, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 550, 41));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblVersion;
    private javax.swing.JPanel pnlRegistro;
    // End of variables declaration//GEN-END:variables
}
